import os
import pandas as pd

enrich_dir = r"c:\Users\001\Desktop\list\04-Enrich"

# Massive Knowledge Base for Art History (Patrons and Painters)
# Format: "Term": ("Location", "Chinese Reason")
kb_full = {
    # --- A ---
    "Accademia Albrizziana": ("Venice", "威尼斯阿尔布里齐亚纳学院"),
    "Accademia degli Umoristi": ("Rome", "罗马幽默学院"),
    "Accademia dei Lincei": ("Rome", "罗马林琴学院"),
    "Accademia del Disegno": ("Florence", "佛罗伦萨迪塞诺学院"),
    "Accademia di Pittura e Scultura": ("Rome", "通常指罗马的法国学院或圣卢卡学院"),
    "Accademia di S. Luca": ("Rome", "罗马圣卢卡学院"),
    "Acqua, Cristoforo dall'": ("Venice", "威尼斯作家"),
    "Adam, James": ("London/Rome", "英国新古典主义建筑师"),
    "Adam, Robert": ("London/Rome", "英国新古典主义建筑师"),
    "Adami, Luigi": ("Rome", "罗马画商"),
    "Adamo, Giovanni": ("Rome", "活跃于罗马的艺术家"),
    "Adda, Cardinal d'": ("Rome", "罗马红衣主教"),
    "Agucchi, Giovanni Battista": ("Rome", "博洛尼亚教士，活跃于罗马的艺术理论家"),
    "Aix-la-Chapelle, Peace of": ("Aachen", "亚琛和约 (1748)"),
    "Albani, Cardinal Annibale": ("Rome", "罗马红衣主教，艺术赞助人"),
    "Albani, Francesco": ("Bologna", "博洛尼亚画派画家"),
    "Albani, Gianfrancesco (Pope Clement XI)": ("Rome", "教皇克莱门特十一世"),
    "Albergati-Capacelli, Francesco": ("Bologna", "博洛尼亚侯爵，剧作家"),
    "Albrizzi, Almorò": ("Venice", "威尼斯贵族"),
    "Albrizzi, Giambattista": ("Venice", "威尼斯出版商"),
    "Aldobrandini, Cardinal Pietro": ("Rome", "罗马红衣主教，重要收藏家"),
    "Aldobrandini, Ippolito (Pope Clement VIII)": ("Rome", "教皇克莱门特八世"),
    "Alexander VII": ("Rome", "教皇亚历山大七世 (Chigi)"),
    "Alexander VIII": ("Rome", "教皇亚历山大八世 (Ottoboni)"),
    "Algardi, Alessandro": ("Rome", "罗马巴洛克雕塑家"),
    "Algarotti, Bonomo": ("Venice", "威尼斯商人，Francesco的兄弟"),
    "Algarotti, Francesco": ("Venice/Berlin", "威尼斯博学家，艺术鉴赏家"),
    "Allegrini, Francesco": ("Rome", "罗马画家"),
    "Altham, James": ("London", "英国赞助人"),
    "Alticchiero (Querini villa)": ("Padua", "帕多瓦附近的别墅"),
    "Altieri palace": ("Rome", "罗马阿尔蒂耶里宫"),
    "Altieri, Don Gasparo": ("Rome", "罗马亲王"),
    "Altieri, Emilio (Pope Clement X)": ("Rome", "教皇克莱门特十世"),
    "Amelot de la Houssaye, A. N.": ("Venice/Paris", "法国历史学家，威尼斯史作者"),
    "Ameyden, Dirk": ("Rome", "活跃于罗马的佛兰芒律师/日记作者"),
    "Amigoni, Jacopo": ("Venice", "威尼斯洛可可画家"),
    "Andreosi, Francesco": ("Rome", "罗马艺术商"),
    "Angeli, Filippo d' (Napoletano)": ("Rome/Naples", "风景画家"),
    "Angeli, Giuseppe": ("Venice", "威尼斯画家 (Piazzetta的学生)"),
    "Angeloni, Francesco": ("Rome", "罗马古董商/作家"),
    "Animuccia, Giovanni": ("Rome", "文艺复兴作曲家"),
    "Anne of Austria, Regent of France": ("Paris", "法国摄政太后"),
    "Anne, Queen of England": ("London", "英国女王"),
    "Antonazzi, Antonio Maria": ("Rome", "罗马艺术家"),
    "Aquaviva, Claudio": ("Rome", "耶稣会总会长"),
    "Arcadia, Society of": ("Rome", "阿卡迪亚学院 (文学社团)"),
    "Arconato, Galeazzo": ("Milan", "米兰收藏家 (拥有达芬奇手稿)"),
    "Ariosto": ("Ferrara", "文艺复兴诗人"),
    "Arlington, Lord": ("London", "英国政治家"),
    "Armanni, G. A.": ("Rome", "罗马文人"),
    "Armanni, Vincenzo": ("Rome", "罗马风景画家"),
    "Arpino, Cavaliere d'": ("Rome", "罗马样式主义晚期画家"),
    "Arrighi-Landini, Orazio": ("Florence", "意大利画家"),
    "Arrighini": ("Lucca", "卢卡建筑师"),
    "Arundel, Lord": ("London", "英国重要艺术收藏家"),
    "Assereto, Gioacchino": ("Genoa", "热那亚巴洛克画家"),
    "Astalli (Pamfili), Camillo": ("Rome", "罗马红衣主教"),
    "Audran, Benoit": ("Paris", "法国版画家"),
    "Augustus II of Poland": ("Dresden/Warsaw", "萨克森选帝侯/波兰国王"),
    "Augustus III of Poland": ("Dresden/Warsaw", "萨克森选帝侯/波兰国王"),
    "Azzolini, Cardinal": ("Rome", "罗马红衣主教 (克里斯蒂娜女王密友)"),

    # --- B ---
    "'Baciccio'": ("Rome", "活跃于罗马 (Gaulli)"),
    "Bernardine Baccinelli": ("Rome", "疑似 Baciccio 变体/相关"),
    "Bacon, Sir Francis": ("London", "英国哲学家/政治家"),
    "Baglione, Giovanni": ("Rome", "罗马巴洛克画家/传记作家"),
    "Baglioni collection": ("Perugia/Rome", "巴利奥尼家族收藏"),
    "Bagnara, Duchess of": ("Rome", "罗马贵族"),
    "Bagutti, Pietro Martire": ("Bologna", "活跃于博洛尼亚的灰泥艺术家"),
    "Baines, Sir Thomas": ("Cambridge/Constantinople", "英国医生/旅行家"),
    "Baker, Thomas": ("London", "英国古董商/收藏家"),
    "Balbi, Paolo Battista": ("Genoa", "热那亚贵族"),
    "Baldi, Lazzaro": ("Rome", "罗马巴洛克画家 (Pietro da Cortona学生)"),
    "Baldinucci, Filippo": ("Florence", "佛罗伦萨艺术史学家"),
    "Baldoini, Giovanni Gasparo": ("Rome", "罗马赞助人"),
    "Balestra, Antonio": ("Verona/Venice", "维罗纳画家"),
    "Balestrieri, Gabriele": ("Rome", "罗马艺术家"),
    "Bambini, Niccolò": ("Venice", "威尼斯画家"),
    "Bamboccianti": ("Rome", "活跃于罗马的风俗画家群体"),
    "Bandinelli, Baccio": ("Florence", "佛罗伦萨雕塑家"),
    "Bandino, Cardinal": ("Rome", "罗马红衣主教"),
    "Baratta, Francesco": ("Rome", "罗马巴洛克雕塑家"),
    "Barbarigo, Caterina": ("Venice", "威尼斯贵族"),
    "Barbarigo, Pietro": ("Venice", "威尼斯贵族"),
    "Barbaro, Antonio": ("Venice", "威尼斯贵族"),
    "Barberini family": ("Rome", "罗马显赫家族 (教皇乌尔班八世)"),
    "Barberini palace": ("Rome", "罗马巴贝里尼宫"),
    "Barberini, Cardinal Antonio": ("Rome", "罗马红衣主教"),
    "Barberini, Cardinal Francesco": ("Rome", "罗马红衣主教"),
    "Barberini, Carlo": ("Rome", "罗马贵族"),
    "Barberini, Maffeo (Pope Urban VIII)": ("Rome", "教皇乌尔班八世"),
    "Barberini, Monsignor Francesco": ("Rome", "罗马教士"),
    "Barberini, Prince Maffeo": ("Rome", "罗马亲王"),
    "Barberini, Taddeo": ("Rome", "罗马亲王"),
    "Barelli, Agostino": ("Bologna", "博洛尼亚建筑师"),
    "Baretti, Giuseppe": ("Turin/London", "意大利文学批评家"),
    "Barnabotti": ("Venice", "威尼斯贫穷贵族阶层"),
    "Barocci, Federico": ("Urbino", "乌尔比诺画派代表"),
    "Baroni, Leonora": ("Rome", "著名歌手/音乐家"),
    "Baronio, Cardinal": ("Rome", "教会史学家"),
    "Bartoli, Pietro Santi": ("Rome", "罗马雕刻家/古董研究者"),
    "Bartolommeo, Fra": ("Florence", "文艺复兴画家"),
    "Basadonna, Cardinal Pietro": ("Rome", "威尼斯籍红衣主教"),
    "Bassanino, Virgilio": ("Venice", "威尼斯画家"),
    "Bassano, Jacopo": ("Venice", "威尼斯画派画家"),
    "Bassi, Francesco (il Cremonese)": ("Bologna", "活跃于博洛尼亚的风景画家"),
    "Batoni, Pompeo": ("Rome", "罗马新古典主义先驱"),
    "Beccari, Dr": ("Bologna", "博洛尼亚学者"),
    "Beccaria, Cesare": ("Milan", "启蒙思想家"),
    "Bedford, John, 4th Duke of": ("London", "英国贵族，大旅行赞助人"),
    "Bella, Stefano della": ("Florence", "佛罗伦萨版画家"),
    "Bellini, Gentile": ("Venice", "威尼斯画派画家"),
    "Bellini, Giovanni": ("Venice", "威尼斯画派大师"),
    "Belloni, Giovanni Antonio": ("Venice", "威尼斯画家"),
    "Bellori, Giovan Pietro": ("Rome", "罗马著名艺术理论家"),
    "Bellotti, Pietro": ("Venice", "威尼斯肖像画家"),
    "Bellotto, Bernardo": ("Venice/Dresden", "威尼斯风景画家 (Canaletto之侄)"),
    "Bellucci, Antonio": ("Venice", "威尼斯洛可可画家"),
    "Bellucci, Giovanni Battista": ("Venice", "威尼斯画家"),
    "Bencovich, Federico": ("Venice/Vienna", "达尔马提亚裔巴洛克画家"),
    "Benedictines": ("Europe", "本笃会 (天主教修会)"),
    "Benefial, Marco": ("Rome", "罗马反巴洛克风格画家"),
    "Bentinck, William": ("London", "英国外交官"),
    "Bentivoglio, Cardinal Guido": ("Rome", "罗马红衣主教，凡·戴克赞助人"),
    "Bentivoglio, Enzo": ("Ferrara/Rome", "费拉拉侯爵"),
    "Bentivoglio, Ippotilo": ("Ferrara", "费拉拉贵族"),
    "Bermis, Cardinal de": ("Rome", "法国驻罗马大使/红衣主教"),
    "Bernardo Strozzi": ("Genoa/Venice", "热那亚/威尼斯巴洛克画家"),
    "Bernini, Domenico": ("Rome", "Gian Lorenzo之子，传记作者"),
    "Bernini, Gian Lorenzo": ("Rome", "罗马巴洛克大师"),
    "Bernini, Pietro": ("Rome", "雕塑家，Gian Lorenzo之父"),
    "Berreguete, Pedro": ("Spain/Urbino", "西班牙画家"),
    "Berrettini, Pietro (Pietro da Cortona)": ("Rome", "罗马巴洛克盛期大师"),
    "Berrettoni, Niccolò": ("Rome", "罗马画家 (Maratta学生)"),
    "Bertos, Francesco": ("Venice", "威尼斯雕塑家/画家"),
    "Bettinelli, Saverio": ("Mantua", "耶稣会士/作家"),
    "Bianchi, Isidoro": ("Turin", "皮埃蒙特画家"),
    "Bianconi, G. L.": ("Bologna/Dresden", "艺术作家/医生"),
    "Biffi, Giambattista": ("Cremona", "克雷莫纳赞助人"),
    "Bigari, Vittorio": ("Bologna", "博洛尼亚画家"),
    "Bingley, Lord": ("London", "英国贵族"),
    "Bizoni, Bernardo": ("Rome", "旅行日记作者"),
    "Blainville, Monsieur de": ("Europe", "旅行家/作家"),
    "Blunt, Sir Anthony": ("London", "现代艺术史学家 (Poussin专家)"),
    "Boccage, Mme de": ("Paris", "法国沙龙女主人"),
    "Bologna": ("Bologna", "意大利城市"),
    "Bombelli Sebastiano": ("Venice", "威尼斯肖像画家"),
    "Bonati, Giovanni": ("Rome", "罗马画家"),
    "Boncampagni, Ugo (Pope Gregory XIII)": ("Rome", "教皇格里高利十三世"),
    "Bonfiglioli collection": ("Bologna", "博洛尼亚收藏"),
    "Boni, Giacomo Antonio": ("Bologna", "博洛尼亚画家"),
    "Book illustration": ("Europe", "书籍插画艺术"),
    "Bordone, Paris": ("Venice", "威尼斯画派画家"),
    "Bordoni, Francesco": ("Florence", "佛罗伦萨雕塑家"),
    "Borghese Palace": ("Rome", "罗马博尔盖塞宫"),
    "Borghese, Camillo (Pope Paul V)": ("Rome", "教皇保罗五世"),
    "Borghese, Cardinal Scipione": ("Rome", "罗马红衣主教，Bernini早期赞助人"),
    "Borgognone, Giacomo (Jacques Courtois)": ("Rome", "以战争画著称的耶稣会画家"),
    "Borgognone, Guglielmo (Guillaume Courtois)": ("Rome", "罗马画家"),
    "Borromeo, Cardinal Federico": ("Milan", "米兰大主教，安布罗西亚图书馆创建者"),
    "Borromini, Francesco": ("Rome", "罗马巴洛克建筑师"),
    "Borzone, Francesco": ("Genoa", "热那亚画家"),
    "Boscarati, Felice": ("Verona", "维罗纳画家"),
    "Boschini, Marco": ("Venice", "威尼斯艺术理论家/画家"),
    "Boscovich, P.": ("Rome", "耶稣会数学家/天文学家"),
    "Bossuet, Jacques-Bénigne": ("Paris", "法国主教/布道家"),
    "Both, Jan": ("Rome/Utrecht", "荷兰意大利派风景画家"),
    "Bottari, Giovanni": ("Rome", "罗马学者/艺术顾问"),
    "Botti, Francesco": ("Florence", "佛罗伦萨画家"),
    "Bouchard, Jean-Jacques": ("Rome", "法国日记作者"),
    "Bouchardon, Edmé": ("Paris", "法国雕塑家"),
    "Boucher, François": ("Paris", "法国洛可可画家"),
    "Bouillon, Cardinal de": ("Rome", "法国红衣主教"),
    "Boulogne, Valentin de": ("Rome", "活跃于罗马的法国卡拉瓦乔派画家"),
    "Bourdon, Sébastien": ("Paris/Rome", "法国画家"),
    "Bracci, Pietro": ("Rome", "罗马巴洛克晚期雕塑家"),
    "Bracciolini, Francesco": ("Rome", "巴洛克诗人 (Barberini赞助)"),
    "Bramante": ("Rome", "文艺复兴建筑师"),
    "Brandi, Giacinto": ("Rome", "罗马巴洛克画家"),
    "Brescia": ("Brescia", "意大利城市"),
    "Brill, Paul": ("Rome", "活跃于罗马的佛兰芒风景画家"),
    "Brosses, Charles de": ("Dijon/Rome", "法国作家，著有《意大利书简》"),
    "Brueghel, Jan": ("Antwerp", "佛兰芒画家"),
    "Brunetti, Gaetano": ("London", "装饰画家"),
    "Bruno, Giordano": ("Rome", "哲学家"),
    "Brustolon, Andrea": ("Venice", "威尼斯木雕家"),
    "Buckingham, Duke of": ("London", "英国白金汉公爵，收藏家"),
    "Buffomalco": ("Florence", "早期画家 (十日谈中人物)"),
    "Bulgarini, Bartolomeo": ("Siena", "锡耶纳画家"),
    "Buonamici, Giovan Francesco": ("Rimini", "里米尼建筑师/画家"),
    "Buonarroti, Michelangelo": ("Rome/Florence", "文艺复兴大师"),
    "Buoncompagni family": ("Bologna/Rome", "博洛尼亚/罗马家族"),
    "Burlington, Lord": ("London", "英国帕拉第奥主义建筑赞助人"),
    "Burnet, Bishop": ("London", "英国历史学家"),
    "Busiri, Giovanni Battista": ("Rome", "罗马风景画家"),
    "Bute, Lord": ("London", "英国首相/赞助人"),
    "Byng, Admiral": ("London", "英国海军上将"),

    # --- C ---
    "Caffi, Ippolito": ("Venice", "威尼斯风景画家"),
    "Caffieri, Jean-Jacques": ("Paris", "法国雕塑家"),
    "Cagnacci, Guido": ("Bologna/Venice", "博洛尼亚画派，后活跃于威尼斯"),
    "Cairo, Francesco": ("Milan/Turin", "伦巴第画家"),
    "Calandrucci, Giacinto": ("Rome", "罗马画家 (Maratta学生)"),
    "Caligari": ("Bologna", "博洛尼亚艺术家"),
    "Callot, Jacques": ("Nancy/Florence", "洛林版画家"),
    "Calvi, Jacopo": ("Bologna", "博洛尼亚画家"),
    "Camassei, Andrea": ("Rome", "罗马画家"),
    "Camerini, Giovanni": ("Mantua", "建筑师"),
    "Cametti, Bernardino": ("Rome", "罗马雕塑家"),
    "Campagna, Girolamo": ("Venice", "威尼斯雕塑家"),
    "Campanella, Tommaso": ("Rome/Paris", "哲学家"),
    "Campeggi, Cardinal": ("Bologna", "博洛尼亚红衣主教"),
    "Campi family": ("Cremona", "克雷莫纳画家家族"),
    "Canaletto": ("Venice/London", "威尼斯风景画家"),
    "Candiani": ("Venice", "威尼斯贵族"),
    "Canini, Giovanni Angelo": ("Rome", "罗马画家/版画家"),
    "Canons (Duke of Chandos)": ("London", "Chandos公爵的庄园"),
    "Canova, Antonio": ("Rome/Venice", "新古典主义雕塑家"),
    "Cantarini, Simone": ("Bologna", "博洛尼亚画家 (Reni学生)"),
    "Canuti, Domenico Maria": ("Bologna/Rome", "博洛尼亚壁画家"),
    "Capitoline Museum": ("Rome", "卡比托利欧博物馆"),
    "Capizucchi, Cardinal": ("Rome", "罗马红衣主教"),
    "Capranica theatre": ("Rome", "罗马卡普拉尼卡剧院"),
    "Capuchins": ("Europe", "嘉布遣会 (天主教修会)"),
    "Caracci, Agostino": ("Bologna/Rome", "卡拉奇兄弟之一，博洛尼亚学院创始人"),
    "Caracci, Annibale": ("Bologna/Rome", "卡拉奇兄弟之一，巴洛克风格先驱"),
    "Caracci, Antonio": ("Bologna", "Agostino之子"),
    "Caracci, Lodovico": ("Bologna", "卡拉奇兄弟之一"),
    "Caravaggio": ("Rome", "巴洛克现实主义先驱"),
    "Carlevaris, Luca": ("Venice", "威尼斯风景画先驱"),
    "Carlone, Carlo": ("Como/Austria", "活跃于中欧的意大利画家"),
    "Carmelites": ("Europe", "加尔默罗会 (天主教修会)"),
    "Carneo, Antonio": ("Venice/Friuli", "威尼斯画派画家"),
    "Carpioni, Giulio": ("Venice/Vicenza", "威尼斯画派画家"),
    "Carriera, Rosalba": ("Venice", "威尼斯粉彩肖像画家"),
    "Casa Santa (Loreto)": ("Loreto", "洛雷托圣屋"),
    "Casali, Cardinal": ("Rome", "罗马红衣主教"),
    "Casanova, Giacomo": ("Venice", "威尼斯冒险家/作家"),
    "Cassana, Niccolò": ("Venice", "威尼斯肖像画家"),
    "Cassini, Giovanni Domenico": ("Paris/Bologna", "天文学家"),
    "Castelli, Francesco": ("Rome", "Borromini的原名"),
    "Castello, Valerio": ("Genoa", "热那亚巴洛克画家"),
    "Castiglione, Baldassarre": ("Mantua/Rome", "《廷臣论》作者"),
    "Castiglione, Giovanni Benedetto": ("Genoa/Rome", "热那亚画家/版画家"),
    "Castro, First and Second Wars of": ("Lazio", "教皇国与帕尔马公国之间的战争"),
    "Catherine the Great of Russia": ("St. Petersburg", "俄国女皇，重要收藏家"),
    "Cavalieri di Santo Stefano": ("Tuscany", "圣斯蒂芬骑士团"),
    "Cavallino, Bernardo": ("Naples", "那不勒斯画派画家"),
    "Cavedone, Giacomo": ("Bologna", "博洛尼亚画派画家"),
    "Caylus, Comte de": ("Paris", "法国古董学家/收藏家"),
    "Cebes": ("Greece", "古希腊哲学家 (Cebes Tablet)"),
    "Celesti, Andrea": ("Venice", "威尼斯巴洛克画家"),
    "Cellini, Benvenuto": ("Florence", "样式主义雕塑家/金匠"),
    "Cerquozzi, Michelangelo": ("Rome", "罗马Bamboccianti画家"),
    "Cerrini, Giovanni Domenico": ("Rome", "佩鲁贾/罗马画家"),
    "Ceruti, Giacomo": ("Brescia", "伦巴第现实主义画家"),
    "Cesarini, Virginio": ("Rome", "罗马诗人/林琴学院成员"),
    "Cesari, Giuseppe (Cavaliere d'Arpino)": ("Rome", "罗马样式主义画家"),
    "Chambers, Sir William": ("London", "英国建筑师"),
    "Champaigne, Philippe de": ("Paris", "法国巴洛克画家"),
    "Chandos, Duke of": ("London", "英国贵族，Canons庄园主"),
    "Charles I of England": ("London", "英国国王，重要收藏家"),
    "Charles II of England": ("London", "英国国王"),
    "Charles III of Naples (Charles VII of Naples)": ("Naples", "那不勒斯国王 (波旁王朝)"),
    "Charles III of Spain": ("Madrid", "西班牙国王"),
    "Charles IV, Emperor": ("Prague", "神圣罗马帝国皇帝"),
    "Charles V, Emperor": ("Madrid/Vienna", "神圣罗马帝国皇帝"),
    "Charles VI, Emperor": ("Vienna", "神圣罗马帝国皇帝"),
    "Charles XII of Sweden": ("Sweden", "瑞典国王"),
    "Charles Emmanuel I of Savoy": ("Turin", "萨伏伊公爵"),
    "Charles Emmanuel III of Savoy": ("Turin", "萨伏伊公爵/撒丁国王"),
    "Chiari, Giuseppe": ("Rome", "罗马画家 (Maratta学生)"),
    "Chiavistelli, Jacopo": ("Florence", "佛罗伦萨透视画家"),
    "Chigi family": ("Rome", "罗马显赫家族 (Siena起源)"),
    "Chigi, Agostino": ("Rome", "罗马银行家，文艺复兴赞助人"),
    "Chigi, Cardinal Flavio": ("Rome", "罗马红衣主教"),
    "Chigi, Fabio (Pope Alexander VII)": ("Rome", "教皇亚历山大七世"),
    "Choiseul, Duc de": ("Paris", "法国政治家/收藏家"),
    "Christina, Queen of Sweden": ("Rome", "瑞典女王，退位后定居罗马"),
    "Church, position of in 17th century": ("Rome", "17世纪教会地位"),
    "Ciampelli, Agostino": ("Rome/Florence", "画家"),
    "Cibber, Colley": ("London", "英国剧作家"),
    "Cicero": ("Rome", "古罗马政治家/演说家"),
    "Cignani, Carlo": ("Bologna", "博洛尼亚画派晚期大师"),
    "Cignaroli, Giambettino": ("Verona", "维罗纳画家"),
    "Cigoli, Lodovico": ("Florence/Rome", "佛罗伦萨巴洛克早期画家"),
    "Cinelli": ("Florence", "佛罗伦萨作家 (Giovanni Cinelli Calvoli)"),
    "Cipriani, Giovanni Battista": ("London", "活跃于伦敦的意大利画家"),
    "Citadella, Alfonso": ("Ferrara", "费拉拉雕塑家"),
    "Claude Lorrain": ("Rome", "活跃于罗马的法国风景画家"),
    "Clement VII": ("Rome", "教皇 (Medici)"),
    "Clement VIII": ("Rome", "教皇克莱门特八世 (Aldobrandini)"),
    "Clement IX": ("Rome", "教皇克莱门特九世 (Rospigliosi)"),
    "Clement X": ("Rome", "教皇克莱门特十世 (Altieri)"),
    "Clement XI": ("Rome", "教皇克莱门特十一世 (Albani)"),
    "Clement XII": ("Rome", "教皇克莱门特十二世 (Corsini)"),
    "Clement XIII": ("Rome", "教皇克莱门特十三世 (Rezzonico)"),
    "Clement XIV": ("Rome", "教皇克莱门特十四世 (Ganganelli)"),
    "Clerisseau, Charles-Louis": ("Rome/Paris", "法国建筑师/水彩画家"),
    "Clovio, Giulio": ("Rome", "微型画家"),
    "Cochin, Charles-Nicolas": ("Paris", "法国版画家/艺术评论家"),
    "Cock, Hieronymus": ("Antwerp", "佛兰芒出版商"),
    "Codagora, Viviano": ("Rome/Naples", "建筑随想画(Capriccio)画家"),
    "Cola da Rienzo": ("Rome", "中世纪罗马政治人物"),
    "Colbert, Jean-Baptiste": ("Paris", "路易十四的财政大臣"),
    "Cole, William": ("London", "英国古董学家"),
    "Coli, Giovanni": ("Lucca/Rome", "卢卡画家，与Gherardi合作"),
    "Colonna family": ("Rome", "罗马古老贵族家族"),
    "Colonna, Cardinal Girolamo": ("Rome", "罗马红衣主教"),
    "Colonna, Constable": ("Rome", "科隆纳家族族长"),
    "Colonna, Filippo": ("Rome", "罗马贵族"),
    "Colonna, Michele": ("Bologna", "博洛尼亚透视画家"),
    "Colonna, Prince Francesco": ("Rome", "科隆纳家族亲王"),
    "Colonna, Prince Lorenzo Onofrio": ("Rome", "科隆纳家族亲王，收藏家"),
    "Competitions": ("Rome", "艺术竞赛 (如圣卢卡学院竞赛)"),
    "Conca, Sebastiano": ("Rome/Naples", "活跃于罗马的那不勒斯画家"),
    "Condivi, Ascanio": ("Rome", "米开朗基罗传记作者"),
    "Congregazione dei Virtuosi": ("Rome", "万神殿艺术社团"),
    "Contarini, Alvise": ("Venice", "威尼斯贵族"),
    "Contarini, Cardinal": ("Venice/Rome", "威尼斯籍红衣主教"),
    "Contarini, Marco": ("Venice", "威尼斯贵族/赞助人"),
    "Conti, Prince de": ("Paris", "法国波旁王朝亲王"),
    "Contracts": ("Europe", "艺术委托合同"),
    "Cooper, Anthony Ashley (Lord Shaftesbury)": ("London", "英国哲学家"),
    "Copley, John Singleton": ("London/Boston", "美国/英国画家"),
    "Corneille, Pierre": ("Paris", "法国剧作家"),
    "Corner family": ("Venice", "威尼斯显赫家族 (Cornaro)"),
    "Corner, Cardinal": ("Venice/Rome", "威尼斯籍红衣主教"),
    "Corradini, Antonio": ("Venice/Naples", "洛可可雕塑家 (蒙纱的基督)"),
    "Correggio": ("Parma", "文艺复兴晚期大师"),
    "Corsini family": ("Florence/Rome", "佛罗伦萨/罗马家族"),
    "Corsini, Cardinal Neri": ("Rome", "罗马红衣主教"),
    "Cortona, Pietro da": ("Rome/Florence", "罗马巴洛克盛期大师"),
    "Coryate, Thomas": ("London", "英国旅行家"),
    "Cosimo I de' Medici": ("Florence", "托斯卡纳大公"),
    "Cosimo II de' Medici": ("Florence", "托斯卡纳大公"),
    "Cosimo III de' Medici": ("Florence", "托斯卡纳大公"),
    "Costa, Lorenzo": ("Ferrara/Mantua", "文艺复兴画家"),
    "Costaguti family": ("Rome", "罗马银行家家族"),
    "Cotte, Robert de": ("Paris", "法国建筑师"),
    "Council of Trent": ("Trent", "特伦托会议 (反宗教改革)"),
    "Courtois, Guillaume": ("Rome", "罗马画家 (Borgognone)"),
    "Courtois, Jacques": ("Rome", "战争画家 (Il Borgognone)"),
    "Cozens, Alexander": ("London", "英国风景画家"),
    "Cozens, John Robert": ("London", "英国水彩画家"),
    "Cremonese": ("Cremona", "克雷莫纳画派"),
    "Crespi, Daniele": ("Milan", "米兰巴洛克画家"),
    "Crespi, Giovanni Battista (Il Cerano)": ("Milan", "米兰巴洛克画家"),
    "Crespi, Giuseppe Maria": ("Bologna", "博洛尼亚风俗画家"),
    "Crespi, Luigi": ("Bologna", "Giuseppe Maria之子，传记作者"),
    "Creti, Donato": ("Bologna", "博洛尼亚洛可可画家"),
    "Crozat, Pierre": ("Paris", "法国金融家/大收藏家"),
    "Cuccina family": ("Venice", "威尼斯家族 (Veronese赞助人)"),
    "Cumberland, Duke of": ("London", "英国贵族"),
    "Customs duty on pictures": ("Rome/Venice", "艺术品关税"),
    "Cybo, Cardinal Alderano": ("Rome", "罗马红衣主教"),

    # --- D ---
    "Dal Pozzo, Cassiano": ("Rome", "著名古董学家/Poussin赞助人"),
    "Danti, Ignazio": ("Rome/Bologna", "地理学家/数学家"),
    "David, Jacques-Louis": ("Paris", "新古典主义大师"),
    "De Brosses, Charles": ("Dijon/Rome", "法国作家"),
    "De Piles, Roger": ("Paris", "法国艺术理论家"),
    "De Thou, Jacques-Auguste": ("Paris", "法国历史学家/收藏家"),
    "Defoe, Daniel": ("London", "英国作家"),
    "Del Rosso family": ("Florence", "佛罗伦萨家族"),
    "Delfino family": ("Venice", "威尼斯家族 (Dolfin)"),
    "Delfino, Cardinal Giovanni": ("Rome/Venice", "红衣主教"),
    "Democritus": ("Greece", "古希腊哲学家"),
    "Denon, Vivant": ("Paris", "卢浮宫首任馆长"),
    "Descartes, René": ("France/Netherlands", "哲学家"),
    "Desportes, Alexandre-François": ("Paris", "法国动物画家"),
    "Devonshire, Duke of": ("London", "英国贵族 (Chatsworth)"),
    "Diamantini, Giuseppe": ("Venice", "巴洛克画家"),
    "Diderot, Denis": ("Paris", "百科全书派哲学家/艺术评论家"),
    "Diziani, Gaspare": ("Venice", "威尼斯洛可可画家"),
    "Dolce, Lodovico": ("Venice", "威尼斯艺术理论家"),
    "Dolci, Carlo": ("Florence", "佛罗伦萨巴洛克画家"),
    "Domenichino (Domenico Zampieri)": ("Rome/Bologna", "博洛尼亚画派，活跃于罗马"),
    "Donato, Leonardo": ("Venice", "威尼斯总督"),
    "Doria family": ("Genoa/Rome", "热那亚/罗马显赫家族"),
    "Doria, Andrea": ("Genoa", "热那亚海军上将/统治者"),
    "Doria, Cardinal": ("Rome", "罗马红衣主教"),
    "Doria, Prince Camillo": ("Rome", "罗马亲王"),
    "Dresden": ("Dresden", "萨克森首府，重要艺术中心"),
    "Dryden, John": ("London", "英国诗人"),
    "Dubois, Cardinal": ("Paris", "法国红衣主教"),
    "Dughet, Gaspard": ("Rome", "活跃于罗马的风景画家 (Poussin的内弟)"),
    "Duquesnoy, François": ("Rome", "活跃于罗马的佛兰芒雕塑家"),
    "Durazzo family": ("Genoa", "热那亚贵族家族"),
    "Durer, Albrecht": ("Nuremberg", "德国文艺复兴大师"),
    "Dusseldorf": ("Dusseldorf", "德国城市，选帝侯驻地"),
    "Dutch artists": ("Rome", "活跃于罗马的荷兰艺术家群体 (Bentvueghels)"),
    "Dyck, Anthony van": ("London/Antwerp", "佛兰芒肖像大师"),

    # --- E ---
    "Eastlake, Sir Charles": ("London", "国家美术馆馆长"),
    "Edwards, Pietro": ("Venice", "威尼斯绘画修复师/行政官员"),
    "Elector Palatine": ("Heidelberg/Mannheim", "普法尔茨选帝侯"),
    "Elizabeth I of England": ("London", "英国女王"),
    "Elsheimer, Adam": ("Rome", "活跃于罗马的德国画家"),
    "Emo family": ("Venice", "威尼斯家族"),
    "English patronage": ("Rome/Venice", "英国大旅行赞助"),
    "English tourists in Italy": ("Italy", "大旅行游客"),
    "Enlightenment in Italy": ("Italy", "意大利启蒙运动"),
    "Epicurus": ("Greece", "古希腊哲学家"),
    "Erasmus": ("Rotterdam", "人文主义学者"),
    "Ercolani, Count": ("Bologna", "博洛尼亚赞助人"),
    "Este family": ("Ferrara/Modena", "埃斯特家族"),
    "Este, Cardinal Alessandro d'": ("Rome", "红衣主教"),
    "Este, Cardinal Ippolito d'": ("Rome/Ferrara", "蒂沃利别墅建造者"),
    "Este, Francesco I d'": ("Modena", "摩德纳公爵"),
    "Este, Isabella d'": ("Mantua", "文艺复兴重要赞助人"),
    "Evelyn, John": ("London", "英国日记作者"),
    "Eximeno, Antonio": ("Rome", "西班牙耶稣会士/音乐理论家"),

    # --- F ---
    "Fabbri, Francesco": ("Bologna", "博洛尼亚艺术家"),
    "Fabbrini, Giuseppe": ("Florence", "佛罗伦萨画家"),
    "Fabriano, Gentile da": ("Florence/Rome", "国际哥特式画家"),
    "Facchetti, Pietro": ("Rome", "肖像画家"),
    "Fachetti": ("Rome", "可能是Pietro Facchetti"),
    "Falda, Giovanni Battista": ("Rome", "罗马版画家 (城市景观)"),
    "Falier family": ("Venice", "威尼斯家族"),
    "Fancelli, Cosimo": ("Rome", "罗马雕塑家"),
    "Fanzago, Cosimo": ("Naples", "那不勒斯巴洛克建筑师"),
    "Farini, Luigi": ("Ravenna", "意大利政治家/历史学家"),
    "Farnese family": ("Parma/Rome", "帕尔马/罗马显赫家族"),
    "Farnese, Cardinal Alessandro": ("Rome", "红衣主教，耶稣会教堂赞助人"),
    "Farnese, Cardinal Odoardo": ("Rome", "法尔内塞家族红衣主教，卡拉奇赞助人"),
    "Farnese, Duke Ranuccio": ("Parma", "帕尔马公爵"),
    "Farnese, Elizabeth (Queen of Spain)": ("Madrid", "西班牙王后"),
    "Fedi, Pio": ("Florence", "19世纪雕塑家"),
    "Fei, Alessandro": ("Florence", "佛罗伦萨画家"),
    "Felibien, André": ("Paris", "法国艺术史学家"),
    "Ferdinand I, Grand Duke of Tuscany": ("Florence", "托斯卡纳大公"),
    "Ferdinand II, Grand Duke of Tuscany": ("Florence", "托斯卡纳大公"),
    "Ferdinand III, Grand Duke of Tuscany": ("Florence", "托斯卡纳大公"),
    "Ferdinand IV of Naples": ("Naples", "那不勒斯国王"),
    "Ferg, Franz de Paula": ("London", "奥地利风景画家"),
    "Fermini": ("Rome", "可能是Fermini家族"),
    "Ferrara": ("Ferrara", "意大利城市，埃斯特家族领地"),
    "Ferrari, Giovanni Andrea": ("Genoa", "热那亚画家"),
    "Ferrari, Gregorio de": ("Genoa", "热那亚洛可可画家"),
    "Ferrari, Luca": ("Padua", "巴洛克画家"),
    "Ferri, Ciro": ("Rome", "罗马巴洛克画家 (Cortona学生)"),
    "Fetti, Domenico": ("Mantua/Venice", "活跃于曼图亚和威尼斯的画家"),
    "Fiammingo (Duquesnoy)": ("Rome", "即 François Duquesnoy"),
    "Ficino, Marsilio": ("Florence", "新柏拉图主义哲学家"),
    "Filicaia, Vincenzo da": ("Florence", "诗人"),
    "Filippi, Sebastiano (Bastianino)": ("Ferrara", "费拉拉画家"),
    "Foggini, Giovanni Battista": ("Florence", "佛罗伦萨晚期巴洛克雕塑家"),
    "Fontana, Carlo": ("Rome", "罗马巴洛克晚期建筑师"),
    "Fontana, Domenico": ("Rome/Naples", "建筑师 (西克斯图斯五世御用)"),
    "Fontana, Lavinia": ("Bologna/Rome", "博洛尼亚女画家"),
    "Fontana, Prospero": ("Bologna", "博洛尼亚样式主义画家"),
    "Fontenelle": ("Paris", "法国作家/启蒙思想家"),
    "Fontezzo": ("Venice", "可能是Fontebasso?"),
    "Forlì": ("Forlì", "意大利城市"),
    "Forond": ("Europe", "未识别"),
    "Foscarini, Marco": ("Venice", "威尼斯总督/作家"),
    "Fragonard, Jean-Honoré": ("Paris", "法国洛可可画家"),
    "Franceschini, Baldassarre (Volterrano)": ("Florence", "佛罗伦萨画家"),
    "Franceschini, Marcantonio": ("Bologna", "博洛尼亚画派画家"),
    "Franchini, Niccolò": ("Siena", "锡耶纳画家"),
    "Francis I of France": ("Paris", "法国国王，文艺复兴赞助人"),
    "Franco, Battista": ("Venice/Rome", "样式主义画家"),
    "François, Guy": ("Le Puy", "法国画家"),
    "Frederick III (Holy Roman Emperor)": ("Vienna", "神圣罗马帝国皇帝"),
    "Frederick IV of Denmark": ("Copenhagen", "丹麦国王"),
    "Frederick the Great": ("Berlin/Potsdam", "普鲁士国王"),
    "French Academy in Rome": ("Rome", "罗马法兰西学院"),
    "French hostility to Italian art": ("Paris", "法国对意大利艺术的排斥"),
    "French patronage": ("Rome", "法国在罗马的赞助"),
    "Frescobaldi, Girolamo": ("Rome", "巴洛克作曲家"),
    "Fuga, Ferdinando": ("Rome/Naples", "18世纪建筑师"),
    "Fumiani, Giovanni Antonio": ("Venice", "威尼斯画家 (San Pantalon天顶画)"),
    "Furini, Francesco": ("Florence", "佛罗伦萨画家 (以女性裸体著称)"),
    "Fuseli, Henry": ("London", "浪漫主义画家"),

    # --- G ---
    "Gabbiani, Anton Domenico": ("Florence", "佛罗伦萨晚期巴洛克画家"),
    "Gaddi, Taddeo": ("Florence", "乔托的学生"),
    "Gaetano, Scipione (Pulzone)": ("Rome", "罗马肖像画家"),
    "Gainsborough, Thomas": ("London", "英国风景/肖像画家"),
    "Galilei, Alessandro": ("Rome/Florence", "建筑师"),
    "Galilei, Galileo": ("Florence/Padua", "天文学家/物理学家"),
    "Galli-Bibiena": ("Bologna", "博洛尼亚剧院设计家族"),
    "Galliani": ("Naples", "可能是Galiani (经济学家)"),
    "Gambara, Lattanzio": ("Brescia", "样式主义画家"),
    "Gandolfi, Gaetano": ("Bologna", "博洛尼亚画家"),
    "Gandolfi, Ubaldo": ("Bologna", "博洛尼亚画家"),
    "Garofalo (Benvenuto Tisi)": ("Ferrara", "费拉拉画派画家"),
    "Garzoni, Giovanna": ("Rome/Florence", "静物/微型画家"),
    "Gasparini, Francesco": ("Venice/Rome", "作曲家"),
    "Gattai": ("Italy", "未识别"),
    "Gaulli, Giovanni Battista (Baciccio)": ("Rome", "活跃于罗马 (Gaulli)"),
    "Gay, John": ("London", "《乞丐歌剧》作者"),
    "Gazzeta Veneta": ("Venice", "威尼斯报纸 (Gozzi)"),
    "Genoa": ("Genoa", "热那亚共和国"),
    "Gentileschi, Artemisia": ("Rome/Naples", "卡拉瓦乔派女画家"),
    "Gentileschi, Orazio": ("Rome/London", "卡拉瓦乔派画家"),
    "George I of England": ("London", "英国国王"),
    "George II of England": ("London", "英国国王"),
    "George III of England": ("London", "英国国王"),
    "Gesuati": ("Venice", "耶稣会士 (Gesuati修会)"),
    "Ghezzi, Giuseppe": ("Rome", "罗马画家/秘书"),
    "Ghezzi, Pier Leone": ("Rome", "罗马讽刺漫画家/画家"),
    "Ghiberti, Lorenzo": ("Florence", "文艺复兴雕塑家 (天堂之门)"),
    "Ghirlandaio, Domenico": ("Florence", "文艺复兴画家"),
    "Ghislandi, Vittore (Fra Galgario)": ("Bergamo", "肖像画家"),
    "Giaquinto, Corrado": ("Rome/Madrid", "洛可可画家"),
    "Gibbon, Edward": ("London/Lausanne", "《罗马帝国衰亡史》作者"),
    "Gibbons, Grinling": ("London", "木雕大师"),
    "Gimignani, Giacinto": ("Rome/Pistoia", "巴洛克画家"),
    "Giordano, Luca": ("Naples/Florence/Madrid", "那不勒斯多产画家"),
    "Giorgione": ("Venice", "威尼斯画派大师"),
    "Giotto": ("Florence", "文艺复兴奠基人"),
    "Giovanelli collection": ("Venice", "威尼斯收藏"),
    "Giovanni da San Giovanni": ("Florence/Rome", "佛罗伦萨壁画家"),
    "Giulio Romano": ("Mantua/Rome", "拉斐尔学生，样式主义大师"),
    "Giustiniani, Marchese Vincenzo": ("Rome", "罗马银行家，卡拉瓦乔赞助人"),
    "Goethe, Johann Wolfgang von": ("Weimar/Rome", "德国大文豪"),
    "Goldoni, Carlo": ("Venice", "威尼斯剧作家"),
    "Goltzius, Hendrick": ("Haarlem", "荷兰版画家"),
    "Gombrich, E. H.": ("London", "现代艺术史学家"),
    "Gondi family": ("Florence", "佛罗伦萨家族"),
    "Ghezzi, Pier Leone": ("Rome", "罗马讽刺漫画家"),
    "Gonzaga family": ("Mantua", "曼图亚统治家族"),
    "Gori, Anton Francesco": ("Florence", "古董学家"),
    "Gozzi, Carlo": ("Venice", "威尼斯剧作家"),
    "Gozzi, Gasparo": ("Venice", "威尼斯作家/记者"),
    "Grand Tour": ("Europe", "大旅行"),
    "Grassi collection": ("Venice", "威尼斯收藏"),
    "Grassi, Nicola": ("Venice", "威尼斯画家"),
    "Gravina, Gian Vincenzo": ("Rome", "阿卡迪亚学院创始人之一"),
    "Grechetto (Castiglione)": ("Genoa", "即 Giovanni Benedetto Castiglione"),
    "Gregory XIII": ("Rome", "教皇格里高利十三世 (Boncompagni)"),
    "Gregory XV": ("Rome", "教皇格里高利十五世 (Ludovisi)"),
    "Grimani family": ("Venice", "威尼斯显赫家族"),
    "Grimani, Cardinal Domenico": ("Venice/Rome", "文艺复兴收藏家"),
    "Grosley, Pierre-Jean": ("Troyes", "法国旅行作家"),
    "Guardi, Francesco": ("Venice", "威尼斯风景画家"),
    "Guardi, Gian Antonio": ("Venice", "威尼斯画家"),
    "Guarini, Guarino": ("Turin", "巴洛克建筑师"),
    "Guercino": ("Bologna/Rome", "圭尔奇诺，博洛尼亚画派大师"),
    "Guerrieri, Giovanni Francesco": ("Fossombrone", "卡拉瓦乔派画家"),
    "Guglielmi, Gregorio": ("Rome/Vienna", "壁画家"),
    "Guidi, Domenico": ("Rome", "罗马巴洛克雕塑家"),
    "Guidobono, Bartolomeo": ("Genoa", "热那亚画家"),
    "Gustavus Adolphus of Sweden": ("Sweden", "瑞典国王"),
    "Gustavus III of Sweden": ("Sweden", "瑞典国王，艺术赞助人"),

    # --- H ---
    "Hackert, Jakob Philipp": ("Naples/Rome", "德国风景画家"),
    "Hamilton, Gavin": ("Rome", "苏格兰新古典主义画家/考古学家"),
    "Hamilton, Sir William": ("Naples", "英国驻那不勒斯大使/收藏家"),
    "Hapsburg family": ("Vienna/Madrid", "哈布斯堡皇室"),
    "Hapsburg patronage": ("Vienna", "哈布斯堡家族赞助"),
    "Haskell, Francis": ("London", "《Patrons and Painters》作者"),
    "Hayman, Francis": ("London", "英国画家"),
    "Henri IV of France": ("Paris", "法国国王"),
    "Henrietta Maria, Queen": ("London", "查理一世王后"),
    "Herculaneum": ("Naples", "赫库兰尼姆古城"),
    "Herrera, Francisco de": ("Seville", "西班牙画家"),
    "Highmore, Joseph": ("London", "英国画家"),
    "Hoare, Prince": ("Bath", "英国画家/作家"),
    "Hogarth, William": ("London", "英国画家/版画家"),
    "Holbein, Hans the Younger": ("London", "德国/英国肖像画家"),
    "Hollis, Thomas": ("London", "英国政治哲学家/收藏家"),
    "Honthorst, Gerrit van": ("Utrecht/Rome", "荷兰卡拉瓦乔派画家"),
    "Hooch, Pieter de": ("Delft", "荷兰风俗画家"),
    "Horace": ("Rome", "古罗马诗人"),
    "Howard, Thomas (Earl of Arundel)": ("London", "阿伦德尔伯爵"),
    "Hudson, Thomas": ("London", "英国肖像画家"),
    "Hume, David": ("Edinburgh", "苏格兰哲学家"),

    # --- I ---
    "Ignatius of Loyola, St.": ("Rome", "耶稣会创始人"),
    "Imago primi saeculi": ("Antwerp", "耶稣会百年纪念册"),
    "Imperial family (Austrian)": ("Vienna", "奥地利皇室"),
    "Imperiali, Cardinal Giuseppe": ("Rome", "罗马红衣主教"),
    "Indecency in art": ("Rome", "艺术中的不雅问题 (反宗教改革)"),
    "Innocent X": ("Rome", "教皇英诺森十世 (Pamfili)"),
    "Innocent XI": ("Rome", "教皇英诺森十一世 (Odescalchi)"),
    "Innocent XII": ("Rome", "教皇英诺森十二世 (Pignatelli)"),
    "Innocent XIII": ("Rome", "教皇英诺森十三世 (Conti)"),
    "Inquisition": ("Rome/Spain", "宗教裁判所"),
    "Isabella Clara Eugenia": ("Brussels", "西属尼德兰总督"),

    # --- J ---
    "James II of England": ("London", "英国国王"),
    "James III of England": ("Rome", "老王位觊觎者 (Stuart)"),
    "Jansenism": ("France", "扬森主义"),
    "Jenkins, Thomas": ("Rome", "英国古董商/银行家"),
    "Jesuits": ("Rome", "耶稣会"),
    "Johann Georg III of Saxony": ("Dresden", "萨克森选帝侯"),
    "Johann Wilhelm, Elector Palatine": ("Dusseldorf", "普法尔茨选帝侯"),
    "Johnson, Samuel": ("London", "英国文人"),
    "Jones, Inigo": ("London", "英国建筑师"),
    "Jordaens, Jacob": ("Antwerp", "佛兰芒画家"),
    "Joseph I, Emperor": ("Vienna", "神圣罗马帝国皇帝"),
    "Joseph II, Emperor": ("Vienna", "神圣罗马帝国皇帝"),
    "Julian the Apostate": ("Rome", "罗马皇帝"),
    "Julius II": ("Rome", "教皇 (Della Rovere)"),
    "Justinus": ("Rome", "古罗马历史学家"),
    "Justus of Ghent": ("Urbino", "佛兰芒画家"),
    "Juvarra, Filippo": ("Turin", "都灵巴洛克建筑师"),

    # --- K ---
    "Kauffmann, Angelica": ("London/Rome", "新古典主义女画家"),
    "Kent, William": ("London", "英国建筑师/园林设计师"),
    "Kevenhuller, Count": ("Vienna", "奥地利外交官"),
    "Kneller, Sir Godfrey": ("London", "宫廷肖像画家"),

    # --- L ---
    "La Harpe": ("Paris", "法国评论家"),
    "La Hyre, Laurent de": ("Paris", "法国画家"),
    "La Teuliere": ("Rome", "法兰西学院院长"),
    "La Tour, Georges de": ("Lorraine", "法国卡拉瓦乔派画家"),
    "Labia collection": ("Venice", "拉比亚家族收藏"),
    "Labia palace": ("Venice", "拉比亚宫 (Tiepolo壁画)"),
    "Laguerre, Louis": ("London", "法国/英国装饰画家"),
    "Lairesse, Gerard de": ("Amsterdam", "荷兰画家/理论家"),
    "Lambert, George": ("London", "英国风景画家"),
    "Lamoignon, Chrétien-François de": ("Paris", "法国政治家"),
    "Lancret, Nicolas": ("Paris", "法国洛可可画家"),
    "Lanfranco, Giovanni": ("Rome/Naples", "巴洛克画家，活跃于罗马和那不勒斯"),
    "Langetti, Giovan Battista": ("Venice", "威尼斯暗色派画家"),
    "Lanzi, Luigi": ("Florence", "艺术史学家"),
    "Largillierre, Nicolas de": ("Paris", "法国肖像画家"),
    "Lazzarini, Gregorio": ("Venice", "威尼斯画家，Tiepolo的老师"),
    "Le Brun, Charles": ("Paris", "路易十四的首席画家"),
    "Le Nôtre, André": ("Paris", "凡尔赛宫园林设计师"),
    "Le Sueur, Eustache": ("Paris", "法国画家"),
    "Legros, Pierre": ("Rome", "法国巴洛克雕塑家"),
    "Leicester, Earl of": ("London", "英国贵族 (Holkham Hall)"),
    "Lely, Sir Peter": ("London", "英国宫廷画家"),
    "Lemoyne, François": ("Paris", "法国洛可可画家"),
    "Leo X": ("Rome", "教皇 (Medici)"),
    "Leo XI": ("Rome", "教皇利奥十一世 (Medici)"),
    "Leonardo da Vinci": ("Milan/Florence/France", "文艺复兴全才"),
    "Leoni, Ottavio": ("Rome", "罗马肖像画家/版画家"),
    "Leopold I, Emperor": ("Vienna", "神圣罗马帝国皇帝"),
    "Leopold, Archduke (later Emperor Leopold II)": ("Florence/Vienna", "托斯卡纳大公/皇帝"),
    "Lepanto, Battle of": ("Lepanto", "勒班陀海战"),
    "Lessing, Gotthold Ephraim": ("Germany", "德国启蒙作家 (拉奥孔)"),
    "Levey, Michael": ("London", "现代艺术史学家"),
    "Liberi, Pietro": ("Venice", "威尼斯画家"),
    "Liechtenstein, Prince": ("Vienna", "列支敦士登亲王，收藏家"),
    "Ligorio, Pirro": ("Rome", "建筑师/古董学家"),
    "Ligozzi, Jacopo": ("Florence", "画家/插画家"),
    "Liotard, Jean-Étienne": ("Geneva", "瑞士粉彩画家"),
    "Lippi, Filippino": ("Florence", "文艺复兴画家"),
    "Lippi, Fra Filippo": ("Florence", "文艺复兴画家"),
    "Locatelli, Andrea": ("Rome", "罗马风景画家"),
    "Lomazzo, Giovanni Paolo": ("Milan", "样式主义理论家"),
    "Lombardi, Alfonso": ("Bologna", "雕塑家"),
    "Longhi, Pietro": ("Venice", "威尼斯风俗画家"),
    "Longhi, Roberto": ("Italy", "现代著名艺术史学家"),
    "Loredan family": ("Venice", "威尼斯家族"),
    "Lorenzetti, Ambrogio": ("Siena", "锡耶纳画家"),
    "Lorenzini": ("Florence", "可能是Lorenzini家族"),
    "Lorrain, Claude": ("Rome", "即 Claude Lorrain"),
    "Lot and his Daughters": ("Bible", "圣经题材"),
    "Loth, Johann Carl": ("Venice", "活跃于威尼斯的德国画家"),
    "Lotto, Lorenzo": ("Venice/Marche", "文艺复兴画家"),
    "Louis XIII": ("Paris", "法国国王"),
    "Louis XIV": ("Paris", "法国国王 (太阳王)"),
    "Louis XV": ("Paris", "法国国王"),
    "Louis XVI": ("Paris", "法国国王"),
    "Louvre": ("Paris", "卢浮宫"),
    "Loyola, St. Ignatius": ("Rome", "耶稣会创始人"),
    "Lucca": ("Lucca", "意大利城市"),
    "Ludovisi, Cardinal Ludovico": ("Rome", "罗马红衣主教，重要收藏家"),
    "Luini, Bernardino": ("Milan", "达芬奇派画家"),
    "Luti, Benedetto": ("Rome", "活跃于罗马的托斯卡纳画家"),

    # --- M ---
    "Mabuse (Jan Gossaert)": ("Flanders", "佛兰芒画家"),
    "Macerata": ("Macerata", "意大利城市"),
    "Machiavelli": ("Florence", "政治哲学家"),
    "Maderno, Carlo": ("Rome", "罗马巴洛克早期建筑师"),
    "Maderno, Stefano": ("Rome", "雕塑家 (圣塞西莉亚像)"),
    "Madrid": ("Madrid", "西班牙首都"),
    "Maffei, Francesco": ("Vicenza", "巴洛克画家"),
    "Maffei, Scipione": ("Verona", "维罗纳学者/作家"),
    "Magalotti, Lorenzo": ("Florence", "科学家/外交官"),
    "Magnasco, Alessandro": ("Genoa/Milan", "热那亚画家，以怪诞风格著称"),
    "Maintenon, Mme de": ("Paris", "路易十四情妇/妻子"),
    "Malvasia, Carlo Cesare": ("Bologna", "博洛尼亚艺术传记作家"),
    "Mancini, Giulio": ("Rome", "医生/鉴赏家/作家"),
    "Mancini, Maria": ("Rome/Paris", "Mazarin侄女，Colonna夫人"),
    "Manfredi, Bartolomeo": ("Rome", "卡拉瓦乔派画家"),
    "Manin country house": ("Passariano", "马宁别墅 (Villa Manin)"),
    "Manin, Lodovico": ("Venice", "末代威尼斯总督"),
    "Mannerist painting": ("Italy", "样式主义绘画"),
    "Mansart, François": ("Paris", "法国建筑师"),
    "Mansart, Jules Hardouin": ("Paris", "凡尔赛宫建筑师"),
    "Mantegna, Andrea": ("Mantua", "文艺复兴大师"),
    "Mantua": ("Mantua", "贡扎加家族统治城市"),
    "Maratta, Carlo": ("Rome", "罗马巴洛克晚期古典主义大师"),
    "Marchesini": ("Bologna", "可能是Marchesini家族"),
    "Marco Aurelio": ("Rome", "罗马皇帝 (骑马像)"),
    "Maria Theresa, Empress": ("Vienna", "奥地利女皇"),
    "Marie Antoinette": ("Paris", "法国王后"),
    "Mariette, Pierre-Jean": ("Paris", "法国收藏家/鉴赏家"),
    "Marini, Giambattista": ("Rome/Paris", "巴洛克诗人"),
    "Marlborough, Duke of": ("London", "英国公爵 (Blenheim Palace)"),
    "Marracci, Ippolito": ("Lucca", "画家"),
    "Martin V": ("Rome", "教皇 (Colonna)"),
    "Martini, Simone": ("Siena", "锡耶纳画家"),
    "Masaccio": ("Florence", "文艺复兴早期大师"),
    "Mascardi, Agostino": ("Rome", "修辞学家"),
    "Massimi, Cardinal Camillo": ("Rome", "罗马红衣主教，Poussin赞助人"),
    "Mastelletta (Giovanni Andrea Donducci)": ("Bologna", "博洛尼亚画家"),
    "Mattei family": ("Rome", "罗马家族"),
    "Mattei, Ciriaco": ("Rome", "卡拉瓦乔赞助人"),
    "Mazarin, Cardinal": ("Paris", "法国红衣主教/首相"),
    "Mazza, Damiano": ("Venice", "威尼斯画家"),
    "Mazzanti, Ludovico": ("Rome/Naples", "画家"),
    "Mazzoni, Guido": ("Modena", "雕塑家"),
    "Mazzoni, Sebastiano": ("Venice", "佛罗伦萨裔威尼斯画家"),
    "Medici family": ("Florence", "佛罗伦萨统治家族"),
    "Medici, Cardinal Leopoldo de'": ("Florence", "美第奇家族红衣主教，收藏家"),
    "Medici, Cosimo III de'": ("Florence", "托斯卡纳大公"),
    "Medici, Ferdinando de' (Grand Prince)": ("Florence", "大亲王，重要赞助人"),
    "Medici, Marie de'": ("Paris", "法国王后"),
    "Memling, Hans": ("Bruges", "佛兰芒画家"),
    "Memmo, Andrea": ("Venice", "威尼斯政治家/作家"),
    "Mengs, Anton Raphael": ("Rome/Madrid", "新古典主义先驱"),
    "Messina": ("Messina", "西西里城市"),
    "Metastasio, Pietro": ("Vienna/Rome", "宫廷诗人/剧作家"),
    "Mezzabarba, Count": ("Pavia", "赞助人"),
    "Michelangelo": ("Rome/Florence", "文艺复兴大师"),
    "Miel, Jan": ("Rome/Turin", "佛兰芒Bamboccianti画家"),
    "Mignard, Pierre": ("Paris", "法国画家"),
    "Milan": ("Milan", "意大利城市"),
    "Milizia, Francesco": ("Rome", "新古典主义理论家"),
    "Milton, John": ("London", "英国诗人"),
    "Mocenigo family": ("Venice", "威尼斯家族"),
    "Mola, Pier Francesco": ("Rome", "活跃于罗马的提契诺画家"),
    "Molière": ("Paris", "法国剧作家"),
    "Molinarolo (Baccinelli)": ("Rome", "即 Baciccio"),
    "Molinos, Miguel de": ("Rome", "静寂主义神学家"),
    "Monnot, Pierre-Étienne": ("Rome", "法国雕塑家"),
    "Montagu, Lady Mary Wortley": ("London/Venice", "英国女作家"),
    "Montaigne, Michel de": ("France", "散文家"),
    "Montesquieu": ("Paris", "启蒙思想家"),
    "Monteverdi, Claudio": ("Venice/Mantua", "巴洛克音乐奠基人"),
    "Monti, Cardinal": ("Milan", "米兰大主教"),
    "Morandi, Giovanni Maria": ("Rome", "画家"),
    "Morazzone (Pier Francesco Mazzucchelli)": ("Milan", "米兰巴洛克画家"),
    "Morelli, Giovanni": ("Italy", "鉴赏家 (Morellian method)"),
    "Moro, Battista del": ("Verona", "画家"),
    "Moroni, Giambattista": ("Bergamo", "肖像画家"),
    "Mazzuoli, Giuseppe": ("Siena/Rome", "雕塑家"),
    "Muratori, Ludovico Antonio": ("Modena", "意大利历史学家/学者"),
    "Murillo, Bartolomé Esteban": ("Seville", "西班牙画家"),
    "Muziano, Girolamo": ("Rome", "样式主义画家"),

    # --- N ---
    "Naldini, Battista": ("Florence", "样式主义画家"),
    "Nanteuil, Robert": ("Paris", "法国版画家"),
    "Naples": ("Naples", "那不勒斯王国"),
    "Napoletano, Filippo": ("Rome/Naples", "风景画家"),
    "Nardini": ("Rome", "可能是Famiano Nardini (考古学家)"),
    "Nattier, Jean-Marc": ("Paris", "法国洛可可肖像画家"),
    "Nazarenes": ("Rome", "拿撒勒画派 (19世纪)"),
    "Negri, Pietro": ("Venice", "威尼斯暗色派画家"),
    "Neri, San Filippo": ("Rome", "奥拉托利会创始人"),
    "Nero, Emperor": ("Rome", "罗马皇帝"),
    "Newcaastle, Duke of": ("London", "英国贵族"),
    "Newton, Sir Isaac": ("London", "英国科学家"),
    "Niceron, Jean-François": ("Paris", "透视学家"),
    "Nogari, Giuseppe": ("Venice", "威尼斯画家 (头像)"),
    "Nollekens, Joseph": ("London", "英国雕塑家"),
    "Norfolk, Duke of": ("London", "英国贵族"),
    "Northumberland, Duke of": ("London", "英国贵族"),
    "Novelli, Pietro": ("Sicily", "西西里画家"),

    # --- O ---
    "Odescalchi family": ("Rome", "罗马显赫家族"),
    "Odescalchi, Benedetto (Pope Innocent XI)": ("Rome", "教皇英诺森十一世"),
    "Odescalchi, Livio": ("Rome", "罗马亲王，克里斯蒂娜女王藏品继承者"),
    "Odoni, Andrea": ("Venice", "收藏家 (Lotto肖像)"),
    "Olivarez, Count-Duke": ("Madrid", "西班牙首相"),
    "Oliver, Isaac": ("London", "微型画家"),
    "Opera": ("Venice/Naples", "歌剧艺术"),
    "Oratorians": ("Rome", "奥拉托利会 (天主教修会)"),
    "Oratorio": ("Rome", "清唱剧"),
    "Orford, Lord (Robert Walpole)": ("London", "英国首相/收藏家"),
    "Orléans, Duke of (Regent)": ("Paris", "法国摄政王/收藏家"),
    "Orsi, Lelio": ("Novellara", "样式主义画家"),
    "Orsini family": ("Rome", "罗马古老贵族家族"),
    "Orsini, Cardinal Benedict": ("Rome", "即教皇本笃十三世"),
    "Osservatore Veneto": ("Venice", "威尼斯刊物 (Gozzi)"),
    "Ostade, Adriaen van": ("Haarlem", "荷兰风俗画家"),
    "Ottoboni, Cardinal Pietro": ("Rome", "罗马红衣主教，重要艺术/音乐赞助人"),
    "Ottoboni, Pope Alexander VIII": ("Rome", "教皇亚历山大八世"),
    "Ovid": ("Rome", "古罗马诗人"),

    # --- P ---
    "Pacheco, Francisco": ("Seville", "西班牙画家/理论家 (Velasquez岳父)"),
    "Padovanino (Alessandro Varotari)": ("Venice", "威尼斯画家 (提香风格复兴)"),
    "Padua": ("Padua", "意大利城市"),
    "Pagani, Gregorio": ("Florence", "画家"),
    "Paglia, Francesco": ("Brescia", "画家/作家"),
    "Paine, James": ("London", "英国建筑师"),
    "Palazzo Pitti": ("Florence", "皮蒂宫"),
    "Palazzo Vecchio": ("Florence", "旧宫"),
    "Palladio, Andrea": ("Vicenza/Venice", "文艺复兴建筑大师"),
    "Pallavicini family": ("Genoa/Rome", "热那亚/罗马家族"),
    "Pallavicini, Cardinal Lazzaro": ("Rome", "红衣主教"),
    "Palma Giovane": ("Venice", "威尼斯样式主义晚期画家"),
    "Palma Vecchio": ("Venice", "威尼斯文艺复兴画家"),
    "Pamfili family": ("Rome", "罗马显赫家族"),
    "Pamfili, Camillo": ("Rome", "帕姆菲利家族亲王"),
    "Pamfili, Cardinal Benedetto": ("Rome", "红衣主教，音乐赞助人"),
    "Pamfili, Giovanni Battista (Pope Innocent X)": ("Rome", "教皇英诺森十世"),
    "Pangaro": ("Italy", "未识别"),
    "Panico, Antonio Maria": ("Bologna", "画家"),
    "Panini, Giovanni Paolo": ("Rome", "罗马维杜塔(Veduta)画家"),
    "Panvinio, Onofrio": ("Rome", "奥斯定会历史学家"),
    "Paolucci, Cardinal": ("Rome", "红衣主教"),
    "Papal states": ("Rome", "教皇国"),
    "Paris": ("Paris", "法国首都"),
    "Parma": ("Parma", "法尔内塞家族领地"),
    "Parmigianino": ("Parma", "样式主义大师"),
    "Parodi, Filippo": ("Genoa", "热那亚巴洛克雕塑家"),
    "Pascoli, Lione": ("Rome", "艺术传记作家"),
    "Pasinelli, Lorenzo": ("Bologna", "博洛尼亚画家"),
    "Passeri, Giovanni Battista": ("Rome", "罗马画家/传记作家"),
    "Passignano, Domenico": ("Florence/Rome", "样式主义画家"),
    "Patronage": ("Europe", "赞助体系"),
    "Paul III": ("Rome", "教皇 (Farnese)"),
    "Paul IV": ("Rome", "教皇 (Carafa)"),
    "Paul V": ("Rome", "教皇保罗五世 (Borghese)"),
    "Pellegrini, Giovanni Antonio": ("Venice", "威尼斯洛可可画家"),
    "Pembroke, Earl of": ("London", "英国贵族 (Wilton House)"),
    "Pepoli family": ("Bologna", "博洛尼亚家族"),
    "Peretti, Felice (Pope Sixtus V)": ("Rome", "教皇西克斯图斯五世"),
    "Pergolesi, Giovanni Battista": ("Naples", "作曲家"),
    "Perino del Vaga": ("Rome/Genoa", "拉斐尔学生"),
    "Perrault, Charles": ("Paris", "法国作家 (古今之争)"),
    "Perrault, Claude": ("Paris", "卢浮宫东立面建筑师"),
    "Perugino": ("Perugia", "拉斐尔的老师"),
    "Peruzzi, Baldassarre": ("Rome/Siena", "建筑师/画家"),
    "Pesaro family": ("Venice", "威尼斯家族"),
    "Pesaro, Giovanni": ("Venice", "威尼斯总督"),
    "Peter the Great": ("St. Petersburg", "俄国沙皇"),
    "Petrarch": ("Italy", "人文主义诗人"),
    "Petworth": ("England", "Petworth House (收藏地)"),
    "Philip II of Spain": ("Madrid", "西班牙国王"),
    "Philip IV of Spain": ("Madrid", "西班牙国王 (Velasquez赞助人)"),
    "Philip V of Spain": ("Madrid", "西班牙国王"),
    "Piacenza": ("Piacenza", "意大利城市"),
    "Piazzetta, Giovanni Battista": ("Venice", "威尼斯画家"),
    "Picart, Bernard": ("Amsterdam", "法国版画家"),
    "Pico della Mirandola": ("Florence", "人文主义哲学家"),
    "Piedmont": ("Turin", "皮埃蒙特地区"),
    "Piero della Francesca": ("Arezzo/Urbino", "文艺复兴大师"),
    "Pietro da Cortona": ("Rome/Florence", "罗马巴洛克盛期大师"),
    "Pigalle, Jean-Baptiste": ("Paris", "法国雕塑家"),
    "Piles, Roger de": ("Paris", "法国艺术理论家"),
    "Pilkington, Matthew": ("London", "艺术词典编纂者"),
    "Pino, Paolo": ("Venice", "艺术理论家"),
    "Piola, Domenico": ("Genoa", "热那亚巴洛克画家"),
    "Piombo, Sebastiano del": ("Rome", "文艺复兴画家"),
    "Piranesi, Giovanni Battista": ("Rome", "威尼斯出生的罗马版画家/建筑师"),
    "Pisa": ("Pisa", "意大利城市"),
    "Pisano, Andrea": ("Florence", "雕塑家"),
    "Pisano, Nicola": ("Pisa", "雕塑家"),
    "Pistoia": ("Pistoia", "意大利城市"),
    "Pitati, Bonifazio de'": ("Venice", "画家"),
    "Pittoni, Giambattista": ("Venice", "威尼斯画家"),
    "Pius IV": ("Rome", "教皇"),
    "Pius V": ("Rome", "教皇"),
    "Pius VI": ("Rome", "教皇 (Braschi)"),
    "Pius VII": ("Rome", "教皇 (Chiaramonti)"),
    "Platnerus": ("Rome", "可能是Platner (考古学家)"),
    "Plato": ("Greece", "古希腊哲学家"),
    "Pliny the Elder": ("Rome", "《自然史》作者"),
    "Poccetti, Bernardino": ("Florence", "样式主义画家"),
    "Poerson, Charles-François": ("Rome", "法兰西学院院长"),
    "Poggio a Caiano": ("Florence", "美第奇别墅"),
    "Polidoro da Caravaggio": ("Rome", "拉斐尔学生"),
    "Polignac, Cardinal de": ("Rome/Paris", "法国红衣主教/收藏家"),
    "Pollaiuolo, Antonio": ("Florence", "文艺复兴艺术家"),
    "Pomerancio (Niccolò Circignani)": ("Rome", "样式主义画家"),
    "Pommersfelden": ("Germany", "Schönborn家族宫殿"),
    "Pompadour, Mme de": ("Paris", "路易十五情妇/赞助人"),
    "Pompeii": ("Naples", "庞贝古城"),
    "Pontormo, Jacopo": ("Florence", "样式主义大师"),
    "Pope, Alexander": ("London", "英国诗人"),
    "Pordenone": ("Venice/Friuli", "文艺复兴画家"),
    "Porta, Giacomo della": ("Rome", "建筑师"),
    "Porta, Guglielmo della": ("Rome", "雕塑家"),
    "Possevino, Antonio": ("Mantua", "耶稣会士"),
    "Poussin, Nicolas": ("Rome", "活跃于罗马的法国古典主义大师"),
    "Pozzo, Andrea": ("Rome/Vienna", "耶稣会画家/建筑师 (透视法大师)"),
    "Prado": ("Madrid", "普拉多博物馆"),
    "Prague": ("Prague", "鲁道夫二世宫廷"),
    "Preti, Mattia": ("Naples/Malta", "卡拉布里亚骑士，活跃于那不勒斯"),
    "Primaticcio, Francesco": ("Fontainebleau", "枫丹白露画派大师"),
    "Procaccini, Giulio Cesare": ("Milan", "米兰巴洛克画家"),
    "Puglieschi": ("Florence", "可能是Puglieschi家族"),
    "Pulzone, Scipione": ("Rome", "肖像画家"),
    "Putti": ("Art", "小天使 (艺术母题)"),

    # --- Q ---
    "Quadratura": ("Italy", "建筑幻觉绘画"),
    "Quarenghi, Giacomo": ("St. Petersburg", "活跃于俄国的意大利建筑师"),
    "Queirolo, Francesco": ("Naples", "雕塑家 (Sansevero礼拜堂)"),
    "Querini, Cardinal Angelo Maria": ("Brescia", "红衣主教/学者"),
    "Quesnoy, François du": ("Rome", "即 Duquesnoy"),
    "Quevedo, Francisco de": ("Madrid", "西班牙作家"),
    "Quirinal Palace": ("Rome", "奎里纳尔宫 (教皇夏宫)"),

    # --- R ---
    "Raggi, Antonio": ("Rome", "罗马巴洛克雕塑家 (Bernini学派)"),
    "Raimondi, Marcantonio": ("Rome", "版画家 (复制拉斐尔作品)"),
    "Rainaldi, Carlo": ("Rome", "巴洛克建筑师"),
    "Ramsay, Allan": ("London", "苏格兰肖像画家"),
    "Raphael": ("Rome", "文艺复兴三杰之一"),
    "Ratti, Carlo Giuseppe": ("Genoa", "热那亚艺术传记作家"),
    "Ravenna": ("Ravenna", "意大利城市"),
    "Reason and fantasy": ("Europe", "理性与幻想 (启蒙运动主题)"),
    "Redi, Francesco": ("Florence", "科学家/诗人"),
    "Reggio": ("Reggio Emilia", "意大利城市"),
    "Regnier, Nicolas": ("Venice", "佛兰芒卡拉瓦乔派画家/商"),
    "Rembrandt": ("Amsterdam", "荷兰黄金时代大师"),
    "Remondini": ("Bassano", "著名出版商家族"),
    "Reni, Guido": ("Bologna/Rome", "博洛尼亚画派大师"),
    "Renieri, Niccolò": ("Venice", "即 Nicolas Regnier"),
    "Residenz (Würzburg)": ("Würzburg", "维尔茨堡官邸 (Tiepolo壁画)"),
    "Restout, Jean": ("Paris", "法国画家"),
    "Reynolds, Sir Joshua": ("London", "英国皇家艺术学院首任院长"),
    "Rezzonico family": ("Venice/Rome", "威尼斯/罗马家族 (Clement XIII)"),
    "Ribera, Jusepe de": ("Naples", "活跃于那不勒斯的西班牙画家"),
    "Riccardi family": ("Florence", "佛罗伦萨显赫家族 (Medici-Riccardi宫)"),
    "Ricci, Marco": ("Venice", "威尼斯风景画家"),
    "Ricci, Sebastiano": ("Venice", "威尼斯洛可可先驱"),
    "Ricci, Seymour de": ("Paris", "目录学家"),
    "Ricciarelli, Daniele (da Volterra)": ("Rome", "米开朗基罗学生"),
    "Richardson, Jonathan": ("London", "英国肖像画家/理论家"),
    "Richelieu, Cardinal": ("Paris", "法国红衣主教/首相"),
    "Ridolfi, Carlo": ("Venice", "威尼斯艺术传记作家"),
    "Rigaud, Hyacinthe": ("Paris", "法国巴洛克肖像画家"),
    "Riminaldi, Orazio": ("Pisa", "比萨画家"),
    "Ripa, Cesare": ("Rome", "图像学家 (Iconologia)"),
    "Roberti, Ercole de'": ("Ferrara", "费拉拉画派"),
    "Robert, Hubert": ("Paris", "法国风景/废墟画家"),
    "Robusti, Jacopo (Tintoretto)": ("Venice", "丁托列托"),
    "Rococo": ("Europe", "洛可可风格"),
    "Romanelli, Giovanni Francesco": ("Rome/Paris", "巴洛克画家"),
    "Romano, Giulio": ("Mantua", "即 Giulio Romano"),
    "Rome": ("Rome", "教皇国首都，艺术中心"),
    "Rosa, Salvator": ("Rome/Florence", "以风景和反叛性格著称的画家"),
    "Rosba, Rosalba": ("Venice", "即 Rosalba Carriera"),
    "Rosichino": ("Rome", "可能是Rosichino (作家)"),
    "Rospigliosi family": ("Rome", "罗马/皮斯托亚家族"),
    "Rospigliosi, Giulio (Pope Clement IX)": ("Rome", "教皇克莱门特九世"),
    "Rosselli, Matteo": ("Florence", "佛罗伦萨画家"),
    "Rossi, Domenico": ("Venice", "建筑师"),
    "Rossi, Mariano": ("Rome", "西西里画家"),
    "Rovere, Francesco Maria della": ("Urbino", "乌尔比诺公爵"),
    "Royal Academy": ("London", "英国皇家艺术学院"),
    "Rubens, Peter Paul": ("Antwerp", "佛兰芒巴洛克大师"),
    "Rudolf II, Emperor": ("Prague", "神圣罗马帝国皇帝，样式主义赞助人"),
    "Ruffo, Don Antonio": ("Messina", "西西里大收藏家 (Rembrandt赞助人)"),
    "Rusconi, Camillo": ("Rome", "罗马巴洛克晚期雕塑家"),
    "Ruspoli, Prince Francesco Maria": ("Rome", "罗马亲王，音乐/艺术赞助人"),
    "Rustici, Giovanni Francesco": ("Florence", "雕塑家"),
    "Ruysdael, Jacob van": ("Haarlem", "荷兰风景画家"),

    # --- S ---
    "Sacchetti family": ("Rome", "罗马银行家家族"),
    "Sacchetti, Cardinal Giulio": ("Rome", "罗马红衣主教"),
    "Sacchi, Andrea": ("Rome", "罗马巴洛克古典主义画家"),
    "Sadeler family": ("Venice/Prague", "版画家家族"),
    "Sagredo family": ("Venice", "威尼斯家族"),
    "Sagredo, Zaccaria": ("Venice", "威尼斯收藏家"),
    "Saint-Non, Abbé de": ("Paris", "法国版画家/旅行家"),
    "Salimbeni, Ventura": ("Siena", "锡耶纳画家"),
    "Salvi, Giovan Battista (Sassoferrato)": ("Rome", "Sassoferrato"),
    "Salviati, Francesco": ("Florence/Rome", "样式主义画家"),
    "Sandrart, Joachim von": ("Rome/Nuremberg", "德国画家/传记作家"),
    "Sanmicheli, Michele": ("Verona", "建筑师"),
    "Sansovino, Andrea": ("Florence/Rome", "雕塑家"),
    "Sansovino, Jacopo": ("Venice", "威尼斯建筑师/雕塑家"),
    "Santi, Giovanni": ("Urbino", "拉斐尔之父"),
    "Saraceni, Carlo": ("Rome/Venice", "卡拉瓦乔派画家"),
    "Sarpi, Paolo": ("Venice", "威尼斯神学家/科学家"),
    "Sarto, Andrea del": ("Florence", "文艺复兴盛期画家"),
    "Sassoferrato (Giovan Battista Salvi)": ("Rome", "以圣母像著称的画家"),
    "Savoy, House of": ("Turin", "萨伏伊王室"),
    "Scamozzi, Vincenzo": ("Venice", "建筑理论家"),
    "Scarlatti, Alessandro": ("Rome/Naples", "巴洛克作曲家"),
    "Scarlatti, Domenico": ("Madrid", "作曲家"),
    "Schedoni, Bartolomeo": ("Parma", "帕尔马画家"),
    "Schulenburg, Marshal": ("Venice", "威尼斯陆军元帅/收藏家"),
    "Sebastiano del Piombo": ("Rome", "文艺复兴画家"),
    "Seghers, Daniel": ("Antwerp", "花卉画家"),
    "Seneca": ("Rome", "斯多葛派哲学家"),
    "Serlio, Sebastiano": ("France/Italy", "建筑理论家"),
    "Serodine, Giovanni": ("Rome", "活跃于罗马的提契诺画家"),
    "Servandoni, Giovanni Niccolò": ("Paris", "建筑师/舞台设计师"),
    "Sestini, Domenico": ("Florence", "钱币学家/旅行家"),
    "Shaftesbury, Lord": ("London", "英国哲学家"),
    "Shakespeare, William": ("London", "英国剧作家"),
    "Signorelli, Luca": ("Cortona", "文艺复兴画家"),
    "Silvani, Gherardo": ("Florence", "建筑师"),
    "Sirani, Elisabetta": ("Bologna", "博洛尼亚女画家"),
    "Sirani, Giovanni Andrea": ("Bologna", "Reni的助手"),
    "Sixtus IV": ("Rome", "教皇 (Della Rovere)"),
    "Sixtus V": ("Rome", "教皇西克斯图斯五世 (Peretti)"),
    "Smith, Joseph (Consul Smith)": ("Venice", "英国驻威尼斯领事，收藏家"),
    "Snyders, Frans": ("Antwerp", "动物/静物画家"),
    "Sodoma, Il": ("Siena", "样式主义画家"),
    "Solimena, Francesco": ("Naples", "那不勒斯巴洛克晚期大师"),
    "Soprani, Raffaele": ("Genoa", "热那亚艺术传记作家"),
    "Spada, Cardinal Bernardino": ("Rome", "罗马红衣主教"),
    "Spada, Lionello": ("Bologna", "卡拉瓦乔派画家"),
    "Spagnoletto (Ribera)": ("Naples", "即 Jusepe de Ribera"),
    "Spanish Succession, War of": ("Europe", "西班牙王位继承战争"),
    "Spinola family": ("Genoa", "热那亚显赫家族"),
    "Spon, Jacob": ("Lyon", "法国考古学家"),
    "Spranger, Bartholomaeus": ("Prague", "鲁道夫二世宫廷画家"),
    "Squarcione, Francesco": ("Padua", "帕多瓦画派创始人"),
    "St. Peter's Basilica": ("Rome", "圣彼得大教堂"),
    "Stanze (Vatican)": ("Rome", "拉斐尔画室"),
    "Stendhal": ("France/Italy", "法国作家"),
    "Stern, Ignaz": ("Rome", "巴洛克画家"),
    "Stoicism": ("Europe", "斯多葛主义"),
    "Stone, Nicholas": ("London", "英国雕塑家"),
    "Strangeways, Mr": ("London", "英国旅行者"),
    "Strange, Sir Robert": ("London", "版画家"),
    "Strozzi family": ("Florence", "佛罗伦萨家族"),
    "Strozzi, Bernardo": ("Genoa/Venice", "热那亚/威尼斯巴洛克画家"),
    "Stuart, House of": ("London/Rome", "斯图亚特王朝"),
    "Stubbs, George": ("London", "英国动物画家"),
    "Subleyras, Pierre": ("Rome", "活跃于罗马的法国画家"),
    "Sustermans, Justus": ("Florence", "美第奇宫廷肖像画家"),
    "Sweden, Queen Christina of": ("Rome", "瑞典女王"),
    "Swinburne, Henry": ("London", "旅行作家"),

    # --- T ---
    "Tacitus": ("Rome", "古罗马历史学家"),
    "Tacca, Pietro": ("Florence", "雕塑家"),
    "Tassi, Agostino": ("Rome", "罗马风景/海景画家 (Claude的老师)"),
    "Tasso, Torquato": ("Ferrara", "《被解放的耶路撒冷》作者"),
    "Tassoni, Alessandro": ("Modena", "诗人"),
    "Tempesta, Antonio": ("Rome", "罗马版画家/画家"),
    "Teniers, David the Younger": ("Antwerp", "佛兰芒风俗画家"),
    "Terbrugghen, Hendrick": ("Utrecht", "荷兰卡拉瓦乔派画家"),
    "Tessin, Nicodemus the Younger": ("Stockholm", "瑞典建筑师"),
    "Testa, Pietro": ("Rome", "罗马画家/版画家"),
    "Theatines": ("Rome", "天主教修会 (Theatines)"),
    "Theodoli, Marchese": ("Rome", "建筑师"),
    "Thornhill, Sir James": ("London", "英国巴洛克壁画家"),
    "Thorvaldsen, Bertel": ("Rome", "丹麦新古典主义雕塑家"),
    "Thuanus (De Thou)": ("Paris", "历史学家"),
    "Tibaldi, Pellegrino": ("Bologna/Milan", "样式主义建筑师/画家"),
    "Tiepolo, Giambattista": ("Venice/Würzburg/Madrid", "威尼斯洛可可壁画大师"),
    "Tiepolo, Giandomenico": ("Venice", "Giambattista之子，风俗画家"),
    "Tiepolo, Lorenzo": ("Venice/Madrid", "Giambattista之子"),
    "Tischbein, J. H. W.": ("Naples", "德国画家 (歌德肖像)"),
    "Titian": ("Venice", "威尼斯画派泰斗"),
    "Tivoli": ("Lazio", "蒂沃利 (哈德良别墅/埃斯特别墅)"),
    "Toledo, Eleonora di": ("Florence", "科西莫一世公爵夫人"),
    "Tommaso da Modena": ("Treviso", "早期画家"),
    "Torelli, Giacomo": ("Venice/Paris", "舞台设计师"),
    "Torrigiani, Pietro": ("London/Spain", "佛罗伦萨雕塑家"),
    "Torso Belvedere": ("Rome", "贝尔维德雷躯干像"),
    "Tosi, Pier Francesco": ("London", "歌唱家/理论家"),
    "Tournehem, Lenormant de": ("Paris", "法国皇家建筑总监"),
    "Trajan's Column": ("Rome", "图拉真柱"),
    "Tremollière, Pierre-Charles": ("Paris", "法国画家"),
    "Trent, Council of": ("Trent", "特伦托会议"),
    "Trevisani, Francesco": ("Rome", "活跃于罗马的威尼斯/罗马画派画家"),
    "Tribolo, Niccolò": ("Florence", "雕塑家/园林设计师"),
    "Tron family": ("Venice", "威尼斯家族"),
    "Troy, Jean-François de": ("Rome", "法兰西学院院长"),
    "Turin": ("Turin", "萨伏伊王朝首都"),
    "Tuscany": ("Florence", "托斯卡纳大公国"),

    # --- U ---
    "Ubertini, Francesco (Bacchiacca)": ("Florence", "样式主义画家"),
    "Uccello, Paolo": ("Florence", "透视法先驱"),
    "Udine": ("Udine", "意大利城市"),
    "Udine, Giovanni da": ("Rome", "拉斐尔助手 (装饰画)"),
    "Uffenbach, Z. C. von": ("Frankfurt", "德国旅行家/收藏家"),
    "Urban VIII": ("Rome", "教皇乌尔班八世 (Barberini)"),
    "Urbino": ("Urbino", "意大利城市，拉斐尔故乡"),
    "Utrecht": ("Utrecht", "荷兰城市 (卡拉瓦乔派中心)"),

    # --- V ---
    "Vaccaro, Andrea": ("Naples", "那不勒斯画家"),
    "Vaga, Perino del": ("Rome/Genoa", "拉斐尔学生"),
    "Valentin de Boulogne": ("Rome", "活跃于罗马的法国卡拉瓦乔派画家"),
    "Valeriano, Pierio": ("Rome", "人文主义者"),
    "Valesio, Giovanni": ("Bologna", "版画家"),
    "Valle, Pietro della": ("Rome", "旅行家"),
    "Van Dyck, Anthony": ("London/Antwerp/Genoa", "佛兰芒肖像大师"),
    "Van Helmont": ("Flanders", "佛兰芒画家"),
    "Van Loo, Carle": ("Paris", "法国画家"),
    "Van Loo, Jean-Baptiste": ("London/Paris", "法国画家"),
    "Van Mander, Karel": ("Haarlem", "北方瓦萨里 (传记作家)"),
    "Van Vianen, Adam": ("Utrecht", "银匠"),
    "Vanderbank, John": ("London", "英国画家"),
    "Vandervelde, Willem": ("London", "海景画家"),
    "Vanni, Francesco": ("Siena", "锡耶纳画家"),
    "Vanvitelli, Gaspare": ("Rome", "荷兰裔罗马风景画家 (Van Wittel)"),
    "Vanvitelli, Luigi": ("Naples", "卡塞塔皇宫建筑师"),
    "Varchi, Benedetto": ("Florence", "历史学家"),
    "Vasari, Giorgio": ("Florence", "画家/建筑师/传记作家"),
    "Vasi, Giuseppe": ("Rome", "罗马版画家 (Piranesi老师)"),
    "Vatican": ("Rome", "梵蒂冈"),
    "Vecchi, Giovanni de'": ("Rome", "样式主义画家"),
    "Vecchia, Pietro della": ("Venice", "威尼斯画家"),
    "Vecellio, Cesare": ("Venice", "服饰史学家 (提香亲戚)"),
    "Velasquez": ("Madrid", "西班牙巴洛克大师"),
    "Venice": ("Venice", "威尼斯共和国"),
    "Venier family": ("Venice", "威尼斯家族"),
    "Venusti, Marcello": ("Rome", "米开朗基罗追随者"),
    "Verona": ("Verona", "意大利城市"),
    "Veronese, Paolo": ("Venice", "威尼斯画派大师"),
    "Verrio, Antonio": ("London", "活跃于英国的意大利壁画家"),
    "Verrocchio, Andrea del": ("Florence", "达芬奇的老师"),
    "Versailles": ("Paris", "凡尔赛宫"),
    "Vertue, George": ("London", "英国版画家/古董学家"),
    "Vesalius": ("Padua", "解剖学家"),
    "Vespucci, Amerigo": ("Florence/Seville", "航海家"),
    "Vicenza": ("Vicenza", "帕拉第奥之城"),
    "Vico, Giambattista": ("Naples", "哲学家"),
    "Vien, Joseph-Marie": ("Paris/Rome", "新古典主义先驱"),
    "Vienna": ("Vienna", "哈布斯堡王朝首都"),
    "Vigée-Lebrun, Élisabeth": ("Paris", "法国女画家"),
    "Vignola, Giacomo Barozzi da": ("Rome", "建筑师/理论家"),
    "Villani, Giovanni": ("Florence", "编年史家"),
    "Villanueva, Juan de": ("Madrid", "西班牙建筑师"),
    "Vinci, Leonardo da": ("Milan/Florence", "文艺复兴全才"),
    "Winckelmann, Johann Joachim": ("Rome", "艺术史之父，新古典主义理论家"),
    "Viola, Giovanni Battista": ("Rome", "博洛尼亚风景画家"),
    "Virgil": ("Rome", "古罗马诗人"),
    "Visconti family": ("Milan", "米兰统治家族"),
    "Visentini, Antonio": ("Venice", "建筑师/版画家"),
    "Vite, Timoteo": ("Urbino", "拉斐尔合作者"),
    "Viterbo": ("Lazio", "意大利城市"),
    "Vitruvius": ("Rome", "古罗马建筑师"),
    "Vittoria, Alessandro": ("Venice", "威尼斯雕塑家"),
    "Vivaldi, Antonio": ("Venice", "巴洛克作曲家"),
    "Vivarini family": ("Venice", "威尼斯画家家族"),
    "Vleughels, Nicolas": ("Rome", "法国学院院长"),
    "Volpato, Giovanni": ("Rome", "版画家"),
    "Voltaire": ("Paris/Geneva", "启蒙思想泰斗"),
    "Volterra, Daniele da": ("Rome", "米开朗基罗学生"),
    "Volterrano (Baldassarre Franceschini)": ("Florence", "佛罗伦萨巴洛克画家"),
    "Vorsterman, Lucas": ("Antwerp", "版画家"),
    "Vos, Cornelis de": ("Antwerp", "肖像画家"),
    "Vos, Maerten de": ("Antwerp", "样式主义画家"),
    "Vouet, Simon": ("Rome/Paris", "法国巴洛克绘画奠基人"),

    # --- W ---
    "Waal, Lucas de": ("Antwerp", "风景画家"),
    "Walpole, Horace": ("London", "英国作家/艺术史学家 (Strawberry Hill)"),
    "Walpole, Sir Robert": ("London", "英国首相/收藏家 (Houghton Hall)"),
    "Wanley, Humfrey": ("London", "图书管理员/古文字学家"),
    "Warburton, William": ("London", "文学评论家"),
    "Ware, Isaac": ("London", "英国建筑师"),
    "Watteau, Antoine": ("Paris", "法国洛可可画家"),
    "Webb, John": ("London", "英国建筑师 (Inigo Jones学生)"),
    "Wedgwood, Josiah": ("Stoke-on-Trent", "陶瓷工业家"),
    "Weenix, Jan Baptist": ("Rome/Utrecht", "荷兰画家"),
    "Wellington, Duke of": ("London", "英国军事家/收藏家"),
    "West, Benjamin": ("London", "美国/英国历史画家"),
    "Weyden, Rogier van der": ("Brussels", "北方文艺复兴大师"),
    "Wharton, Lord": ("London", "凡·戴克赞助人"),
    "Wheatley, Francis": ("London", "英国画家"),
    "Whistler, James McNeill": ("London", "19世纪画家"),
    "White, Robert": ("London", "版画家"),
    "Whitehall Palace": ("London", "英国皇宫"),
    "Wicart, Nicolaas": ("Utrecht", "风景画家"),
    "Wickhoff, Franz": ("Vienna", "维也纳学派艺术史家"),
    "Widmann family": ("Venice", "威尼斯家族"),
    "Wieland, C. M.": ("Weimar", "德国诗人"),
    "Wilkie, David": ("London", "苏格兰风俗画家"),
    "William III of England": ("London", "英国国王"),
    "Wilton, Joseph": ("London", "雕塑家"),
    "Winchester": ("England", "英国城市"),
    "Windsor Castle": ("Windsor", "英国皇室城堡"),
    "Witt, Johan de": ("The Hague", "荷兰政治家"),
    "Wittkower, Rudolf": ("London/USA", "巴洛克艺术史权威"),
    "Woffington, Peg": ("London", "女演员"),
    "Wolsey, Cardinal": ("London", "亨利八世的大臣"),
    "Wood, Robert": ("London", "帕尔米拉遗址发现者"),
    "Wootton, John": ("London", "英国运动/风景画家"),
    "Wotton, Sir Henry": ("Venice", "英国驻威尼斯大使/建筑理论家"),
    "Wouverman, Philips": ("Haarlem", "荷兰画家 (马匹题材)"),
    "Wren, Sir Christopher": ("London", "英国建筑师 (圣保罗大教堂)"),
    "Wright of Derby, Joseph": ("Derby", "英国画家 (光影效果)"),
    "Wright, Michael": ("London", "肖像画家"),
    "Wriothesley, Henry (Earl of Southampton)": ("London", "莎士比亚赞助人"),
    "Wtewael, Joachim": ("Utrecht", "样式主义画家"),
    "Wulfraet, Matthijs": ("Amsterdam", "风俗画家"),
    "Wurhzburg": ("Würzburg", "德国城市"),
    "Würzburg Residenz": ("Würzburg", "维尔茨堡官邸"),
    "Wyatt, James": ("London", "新哥特式建筑师"),
    "Wynants, Jan": ("Haarlem", "风景画家"),

    # --- X ---
    "Xavier, St. Francis": ("Asia", "耶稣会传教士"),
    "Ximenes, Cardinal": ("Spain", "西班牙红衣主教"),

    # --- Y ---
    "York, Duke of": ("London", "约克公爵"),
    "Young, Arthur": ("London", "农业作家/旅行家"),
    "Young, Edward": ("London", "诗人 (《夜思》)"),
    "Ypres": ("Flanders", "伊普尔"),

    # --- Z ---
    "Zaccaria, St. Anthony": ("Milan", "巴尔纳伯会创始人"),
    "Zachtleven, Herman": ("Utrecht", "风景画家"),
    "Zais, Giuseppe": ("Venice", "威尼斯风景画家"),
    "Zamboni, Giovanni": ("Rome", "作曲家"),
    "Zampieri, Domenico (Domenichino)": ("Rome/Bologna", "即 Domenichino"),
    "Zanchi, Antonio": ("Venice", "威尼斯暗色派画家"),
    "Zanetti, Anton Maria": ("Venice", "威尼斯鉴赏家/版画家"),
    "Zanetti, Girolamo": ("Venice", "作家"),
    "Zanotti, Giampietro": ("Bologna", "博洛尼亚画家/传记作家"),
    "Zarlino, Gioseffo": ("Venice", "音乐理论家"),
    "Zatta, Antonio": ("Venice", "出版商"),
    "Zeuxis": ("Greece", "古希腊画家"),
    "Ziani, Sebastiano": ("Venice", "威尼斯总督"),
    "Zocchi, Giuseppe": ("Florence", "佛罗伦萨维杜塔画家"),
    "Zoffany, Johan": ("London", "德国/英国画家"),
    "Zola, Giuseppe": ("Ferrara", "风景画家"),
    "Zompini, Gaetano": ("Venice", "版画家"),
    "Zuccarelli, Francesco": ("Venice/London", "风景画家"),
    "Zuccaro, Federico": ("Rome", "罗马样式主义晚期画家/理论家"),
    "Zuccaro, Taddeo": ("Rome", "样式主义画家"),
    "Zucchi, Antonio": ("London/Rome", "装饰画家 (Kauffmann丈夫)"),
    "Zumbo, Gaetano": ("Florence", "蜡塑解剖学家"),
    "Zurbaran, Francisco de": ("Seville", "西班牙巴洛克画家"),

    # --- Second Pass Variations ---
    "Smith, Joseph": ("Venice", "英国驻威尼斯领事，收藏家"),
    "Pozzo, Cassiano dal": ("Rome", "著名古董学家/Poussin赞助人"),
    "Guercino (Francesco Barbieri)": ("Bologna/Rome", "圭尔奇诺，博洛尼亚画派大师"),
    "Medici, Grand Prince Ferdinand de'": ("Florence", "大亲王，重要赞助人"),
    "Zanetti, A. M., the Elder": ("Venice", "威尼斯鉴赏家/版画家"),
    "Schulenburg, Marshal Johann Matthias": ("Venice", "威尼斯陆军元帅/收藏家"),
    "Bracciano, Paolo Giordona II Orsini, Duke of": ("Rome", "奥尔西尼家族公爵"),
    "Massimi, Cardinal Camillo (Carlo)": ("Rome", "罗马红衣主教，Poussin赞助人"),
    "Querini, Angelo": ("Venice", "威尼斯参议员/改革家"),
    "Roomer, Gaspar": ("Naples", "佛兰芒裔那不勒斯大收藏家"),
    "Farsetti, Filippo": ("Venice", "威尼斯收藏家 (Farsetti宫)"),
    "Lodoli, Padre Carlo": ("Venice", "建筑理论家 (功能主义先驱)"),
    "Pittoni, Giovan Battista": ("Venice", "威尼斯画家"),
    "Romanelli, Giovan Francesco": ("Rome/Paris", "巴洛克画家"),
    "Barberini, Cardinal Francesco (nephew to Urban VIII)": ("Rome", "罗马红衣主教"),
    "Caravaggio, Michelangelo da": ("Rome", "巴洛克现实主义先驱"),
    "McSwiny, Owen": ("Venice/London", "爱尔兰剧院经理/艺术经纪人"),
    "Pasquali, Giambattista": ("Venice", "威尼斯出版商 (Smith赞助)"),
    "Streit, Sigismund": ("Venice", "德国商人在威尼斯，赞助人"),
    "Barberini, Cardinal Antonio (nephew to Urban VIII)": ("Rome", "罗马红衣主教"),
    "Cimaroli, Giovan Battista": ("Venice", "威尼斯风景画家"),
    "Dyck, Sir Anthony Van": ("London/Antwerp", "佛兰芒肖像大师"),
    "Johann Wilhelm, Elector Palatinate": ("Dusseldorf", "普法尔茨选帝侯"),
    "Bellori, Gian Pietro": ("Rome", "罗马著名艺术理论家"),
    "Carpio, Marchese Del": ("Naples/Madrid", "西班牙驻那不勒斯总督/收藏家"),
    "Conti, Antonio": ("Venice", "威尼斯学者/作家"),
    "Oliva, Gian Paolo": ("Rome", "耶稣会总会长"),
    "Shaftesbury, 3rd Earl of": ("London", "英国哲学家"),
    "Vannini, Ottavio": ("Florence", "佛罗伦萨画家"),
    "Zanetti, A. M., the Younger": ("Venice", "威尼斯图书管理员/作家"),
    "Augustus III of Poland (Frederick Augustus II, Elector of Saxony)": ("Dresden/Warsaw", "萨克森选帝侯/波兰国王"),
    "Carlevarijs, Luca": ("Venice", "威尼斯风景画先驱"),
    "Codazzi, Viviano": ("Rome/Naples", "建筑随想画画家"),
    "David, Ludovico": ("Rome/Venice", "卢加诺画家/理论家"),
    "Melanconici, Niccolò": ("Naples", "那不勒斯收藏家"),
    "Novelli, Pietro Antonio": ("Venice", "威尼斯画家/版画家"),
    "Ottoboni, Cardinal Pietro (nephew to Pope Alexander VIII)": ("Rome", "罗马红衣主教，重要艺术/音乐赞助人"),
    "Ribera, Giuseppe": ("Naples", "即 Jusepe de Ribera"),
    "Roncalli, Cristoforo (Pomerancio)": ("Rome", "样式主义画家"),
    "Ruffo, Cardinal Tommaso": ("Ferrara/Rome", "红衣主教/艺术赞助人"),
    "Sasso, Giuseppe Maria": ("Venice", "威尼斯艺术商/修复师"),
    "Barberini, Carlo (brother to Urban VIII)": ("Rome", "罗马贵族"),
    "Carracci, Annibale": ("Bologna/Rome", "卡拉奇兄弟之一"),
    "Correr, Teodoro": ("Venice", "威尼斯收藏家 (Correr博物馆)"),
    "Fumiani, Giannantonio": ("Venice", "威尼斯画家"),
    "Laer, Pieter Van": ("Rome", "Bamboccianti领袖 (Il Bamboccio)"),
    "Ludovisi, Ludovico (nephew to Pope Gregory XV)": ("Rome", "罗马红衣主教，重要收藏家"),
    "Manfrin, Girolamo": ("Venice", "威尼斯烟草商/大收藏家"),
    "Churches": ("Europe", "教堂建筑"),
    "Art exhibitions": ("Europe", "艺术展览"),

    # --- Third Pass Variations (Top 50 Missing) ---
    "Marino, Giambattista": ("Rome/Paris", "巴洛克诗人"),
    "Pamfili, Prince Camillo (nephew to Pope Innocent X)": ("Rome", "帕姆菲利家族亲王"),
    "Pamfili, Gianbattista (Pope Innocent X)": ("Rome", "教皇英诺森十世"),
    "Pisani, Giorgio": ("Venice", "威尼斯贵族/改革家"),
    "Portland, Henry, first Duke of": ("London", "英国贵族"),
    "Religious orders, patronage by": ("Europe", "宗教修会赞助"),
    "Rosso, Andrea del": ("Florence", "佛罗伦萨赞助人"),
    "Sacchetti, Marcello": ("Rome", "罗马银行家/赞助人"),
    "Sole, Giovan Gioseffo dal": ("Bologna", "博洛尼亚画家"),
    "Spadaro, Micco": ("Naples", "那不勒斯画家 (Gargiulo)"),
    "Valeriani, Domenico and Giuseppe": ("Venice", "威尼斯透视画家兄弟"),
    "Vianello, Dr Giovanni": ("Venice", "威尼斯收藏家"),
    "Chandos, Grey Brydges, 5th Lord": ("London", "英国贵族"),
    "Chigi, Cardinal Flavio (nephew to Pope Alexander VII)": ("Rome", "罗马红衣主教"),
    "Colonna, Lorenzo Onofrio": ("Rome", "科隆纳家族亲王"),
    "Corner, Flaminio": ("Venice", "威尼斯历史学家"),
    "Daun, Count": ("Naples/Vienna", "奥地利驻那不勒斯总督"),
    "Fanelli, Francesco": ("Genoa/London", "雕塑家"),
    "Ferrerio, Andrea": ("Milan", "雕塑家"),
    "Fontebasso, Francesco": ("Venice", "威尼斯画家"),
    "Franceschini, Baldassare": ("Florence", "佛罗伦萨画家 (Volterrano)"),
    "Gennari, Benedetto": ("Bologna/London", "博洛尼亚画家 (Guercino侄子)"),
    "German patronage": ("Rome/Germany", "德国赞助"),
    "Giambologna": ("Florence", "样式主义雕塑大师"),
    "Longhi, Alessandro": ("Venice", "威尼斯肖像画家"),
    "Loth, Johann Karl": ("Venice", "活跃于威尼斯的德国画家"),
    "Maggiotto, Francesco": ("Venice", "威尼斯画家"),
    "Maidalchini, Donna Olimpia": ("Rome", "英诺森十世的嫂子/权贵"),
    "Marucelli, Francesco": ("Florence/Rome", "佛罗伦萨学者/藏书家"),
    "Matteis, Paolo de": ("Naples", "那不勒斯画家"),
    "Mei, Bernardino": ("Siena/Rome", "锡耶纳/罗马画家"),
    "Monterey, Count of": ("Naples", "西班牙驻那不勒斯总督"),
    "Nomé, François ('Monsù Desiderio')": ("Naples", "以描绘废墟著称的画家"),
    "Richmond, Duke of": ("London", "英国贵族"),
    "Rosso, Lorenzo del": ("Florence", "佛罗伦萨赞助人"),
    "Savoy, Prince Eugene of": ("Vienna", "奥地利元帅/大收藏家"),
    "Spanish patronage": ("Rome/Spain", "西班牙赞助"),
    "Strange, John": ("Venice/London", "英国驻威尼斯居民/收藏家"),
    "Tessin, Count Carl Gustav": ("Stockholm", "瑞典外交官/收藏家"),
    "Tiepolo, Gian Domenico": ("Venice", "Giambattista之子"),
    "Toni, Don Pietro Antonio": ("Venice", "威尼斯赞助人"),
    "Aldobrandini, Cardinal Pietro (nephew of Pope Clement VIII)": ("Rome", "罗马红衣主教"),
    "Art dealers": ("Europe", "艺术商人"),
    "Augustus II of Poland (Frederick Augustus I, Elector of Saxony)": ("Dresden", "萨克森选帝侯"),
    "Brugiori, Domenico": ("Lucca", "卢卡画家"),
    "Brusoni, Girolamo": ("Venice", "威尼斯作家"),
    "Buonaccorsi, Raimondo": ("Macerata", "马切拉塔伯爵/赞助人"),
    "Campbell, Colen": ("London", "英国建筑师 (Vitruvius Britannicus)"),
    "Carpaccio, Vittore": ("Venice", "威尼斯文艺复兴画家"),
    "Cigoli, Ludovico": ("Florence/Rome", "佛罗伦萨画家"),

    # --- Fourth Pass Variations (Top 50 Missing) ---
    "Colonna palace": ("Rome", "罗马科隆纳宫"),
    "Conti, Stefano": ("Lucca/Rome", "卢卡画家"),
    "Contini, Giovanni Battista": ("Rome", "巴洛克建筑师"),
    "Dardani, Antonio": ("Bologna", "博洛尼亚画家"),
    "Dolfin family": ("Venice", "威尼斯多尔芬家族"),
    "Dorigny, Louis": ("Paris/Verona", "法国画家，活跃于意大利"),
    "Effetti, Antonio degli": ("Rome", "罗马赞助人"),
    "Farnese, Ranuccio II, Duke of Parma": ("Parma", "帕尔马公爵"),
    "Florence": ("Florence", "佛罗伦萨"),
    "Foscarini family": ("Venice", "威尼斯福斯卡里尼家族"),
    "Fountaine, Sir Andrew": ("London", "英国收藏家 (Narford Hall)"),
    "Francavilla, Pietro": ("Florence/Paris", "佛罗伦萨/法国雕塑家"),
    "Galiani, Abate": ("Naples/Paris", "那不勒斯经济学家/外交官"),
    "Gallacini, Teofilo": ("Siena", "锡耶纳学者/建筑理论家"),
    "German princes, taste in art": ("Germany", "德国王公的艺术品味"),
    "Gherardi, Filippo": ("Lucca/Rome", "卢卡画家"),
    "Gori, A. F.": ("Florence", "佛罗伦萨古董学家 (Anton Francesco)"),
    "Guarana, Giacomo": ("Venice", "威尼斯画家"),
    "Guicciardini, Francesco": ("Florence", "文艺复兴历史学家"),
    "Houdon, Jean-Antoine": ("Paris", "法国新古典主义雕塑家"),
    "Huber, Jean": ("Geneva", "瑞士画家/剪影艺术家"),
    "Lancellotti, Abate": ("Rome", "罗马学者"),
    "Lena, Abate Giacomo della": ("Venice", "威尼斯古董商"),
    "Liechtenstein family": ("Vienna", "列支敦士登家族"),
    "Lovisa, Domenico": ("Venice", "威尼斯版画家"),
    "Manchester, Lord": ("London", "英国贵族"),
    "Marchesini, Alessandro": ("Verona/Venice", "维罗纳画家"),
    "Mattei, Tommaso": ("Rome", "罗马建筑师"),
    "Messina, Antonello da": ("Messina/Venice", "文艺复兴早期大师"),
    "Monaco, Pietro": ("Venice", "威尼斯版画家"),
    "Muratori, L. A.": ("Modena", "历史学家 (Ludovico Antonio)"),
    "Nazari, Bartolommeo": ("Venice", "威尼斯肖像画家"),
    "Negroni, Cardinal Giovan Francesco": ("Rome", "罗马红衣主教"),
    "Non, Dominique De (Dominique Vivant-Denon)": ("Paris", "卢浮宫首任馆长"),
    "Orleans, Philippe d', Regent": ("Paris", "法国摄政王"),
    "Pannini, Giovanni Paolo": ("Rome", "罗马维杜塔画家"),
    "Paolini, Pietro": ("Lucca", "卢卡画家 (卡拉瓦乔派)"),
    "Paris, Venetian 18th-century artists in": ("Paris", "巴黎的威尼斯艺术家"),
    "Parmigianino, Francesco": ("Parma", "样式主义大师"),
    "Peretti-Montalto, Cardinal Alessandro": ("Rome", "罗马红衣主教"),
    "Permoser, Balthasar": ("Dresden/Florence", "巴洛克雕塑家"),
    "Pesne, Antoine": ("Berlin", "普鲁士宫廷画家"),
    "Piola, Paolo Girolamo": ("Genoa", "热那亚画家"),
    "Provincial centres of art patronage": ("Italy", "省级艺术赞助中心"),
    "Puget, Pierre": ("Marseille/Genoa", "法国巴洛克雕塑家/画家"),
    "Rambaldi, Carlo Antonio": ("Bologna", "博洛尼亚画家"),
    "Rapparini, Giorgio Maria": ("Bologna/Dusseldorf", "宫廷秘书/歌剧词作者"),
    "Ricci, Giovanni": ("Rome", "红衣主教"),
    "Riminaldi": ("Pisa", "比萨画家 (Orazio Riminaldi)"),
    "Rossi, Carlo de'": ("Rome", "建筑师"),

    # --- Fifth Pass Variations (Top 50 Missing) ---
    "San Giovanni, Giovanni da": ("Florence", "佛罗伦萨壁画家"),
    "Scaramuccia, Luigi": ("Perugia/Milan", "巴洛克画家/传记作家"),
    "Serra, Mgr Giacomo": ("Rome", "教皇财务官/鲁本斯赞助人"),
    "Storer, Cristoforo": ("Milan", "巴洛克画家"),
    "Strada, Famiano": ("Rome", "耶稣会历史学家"),
    "Strudel, Peter": ("Vienna", "奥地利雕塑家/画家"),
    "Temanza, Tommaso": ("Venice", "新古典主义建筑师/作家"),
    "Théodon, Jean Baptiste": ("Rome", "法国巴洛克雕塑家"),
    "Torelli, Felice": ("Bologna", "博洛尼亚画家"),
    "Tura, Cosimo": ("Ferrara", "费拉拉画派创始人"),
    "Turchi, Alessandro": ("Verona/Rome", "维罗纳画家 (l'Orbetto)"),
    "Urbino, devolution to Papacy": ("Urbino", "乌尔比诺归入教皇国"),
    "Vatican palace": ("Rome", "梵蒂冈宫"),
    "Venezia, Padre Antonio da": ("Venice", "威尼斯神职人员"),
    "Vermeer, Johannes": ("Delft", "荷兰黄金时代大师"),
    "Webster, John": ("London", "英国剧作家"),
    "Werff, Adrian van der": ("Rotterdam", "荷兰画家"),
    "Wynne, Giustiniana (Mme Rosenberg)": ("Venice", "英意混血女作家"),
    "Albrizzi, Almorò": ("Venice", "威尼斯贵族"),
    "Barberini, Cardinal Antonio (brother to Urban VIII) (Cardinal di S. Onofrio)": ("Rome", "罗马红衣主教"),
    "Barberini, Monsignor Francesco (uncle to Urban VIII)": ("Rome", "罗马教士"),
    "Barberini, Prince Maffeo (son of Taddeo Barberini)": ("Rome", "罗马亲王"),
    "Barberini, Taddeo (nephew to Urban VIII)": ("Rome", "罗马亲王"),
    "Bartoli, Pietro Santo": ("Rome", "罗马雕刻家/古董研究者"),
    "Bracciano, Duke of": ("Rome", "奥尔西尼家族公爵"),
    "Bramante, Donato": ("Rome", "文艺复兴建筑师"),
    "Bramer, Leonard": ("Delft", "荷兰画家"),
    "Brand, Johannes Christian": ("Vienna", "奥地利风景画家"),
    "Breughel, Abram": ("Naples", "佛兰芒静物画家"),
    "Breughel, Velvet": ("Antwerp", "即 Jan Brueghel the Elder"),
    "Breuil, Toussaint du": ("Paris", "第二枫丹白露画派画家"),
    "Brosses, Président Charles De": ("Dijon/Rome", "法国作家"),
    "Brühl, Count": ("Dresden", "萨克森首相/收藏家"),
    "Brunelleschi, Filippo": ("Florence", "文艺复兴建筑先驱"),
    "Brusasorci, Felice": ("Verona", "维罗纳画家"),
    "Buckingham, Charles Villiers, Duke of": ("London", "英国白金汉公爵"),
    "Buckingham, John Sheffield, Duke of": ("London", "英国白金汉公爵"),
    "Buonaccorsi, Count Orlando": ("Macerata", "马切拉塔贵族"),
    "Buonaccorsi, Cardinal Simone": ("Macerata", "红衣主教"),
    "Burnacini, Lodovico Ottavio": ("Vienna", "舞台设计师/建筑师"),
    "Burrini, Giovanni Antonio": ("Bologna", "博洛尼亚画家"),

    # --- Sixth Pass Variations (Single Instance Targets) ---
    "Albrizzi, Almor¨°": ("Venice", "威尼斯贵族 (Almorò Albrizzi)"),
    "Anti-papal satire in reign of Alexander VII": ("Rome", "罗马反教皇讽刺"),
    "'Artistic temperament', development of concept": ("Europe", "艺术气质概念的发展"),
    "Artist's position in society, Andrea Memmo on": ("Venice", "艺术家社会地位 (Memmo观点)"),
    "Artists, status of in 17th-century Rome": ("Rome", "17世纪罗马艺术家地位"),
    "Bracciano, Paolo Giordano I Orsini, Duke of": ("Rome", "奥尔西尼家族公爵"),
    "Breval, John": ("London", "英国旅行作家"),
    "Brienne, Lomenie de": ("Paris", "法国政治家/收藏家"),
    "Brosse, Salomon de": ("Paris", "法国建筑师 (卢森堡宫)"),
    "Brydges, Grey": ("London", "英国贵族 (Chandos家族)"),
    "Cambiaso, Luca": ("Genoa", "热那亚样式主义画家"),
    "Camerata, Giuseppe": ("Venice", "威尼斯微型画家/版画家"),
    "Caracciolo, Giovanni Battista": ("Naples", "那不勒斯卡拉瓦乔派画家 (Battistello)"),
    "Caravaggio, Polidoro da": ("Rome", "拉斐尔学生"),
    "Carlisle, Earl of": ("London", "英国贵族"),
    "Carlone, Gianandrea": ("Genoa/Rome", "热那亚画家"),
    "Caroselli, Angelo": ("Rome", "罗马巴洛克画家"),
    "Carpi, Ugo da": ("Rome/Venice", "明暗木刻版画先驱"),
    "Carracci, Ludovico": ("Bologna", "卡拉奇兄弟之一"),
    "Casanova de Seingalt, Jacques": ("Venice", "即 Giacomo Casanova"),
    "Cassana, Giovanni Agostino": ("Venice", "威尼斯画家 (Genoese origin)"),
    "Cavagna, Giampaolo": ("Bergamo", "贝加莫画家"),
    "Ceresa, Carlo": ("Bergamo", "贝加莫肖像画家"),
    "Cervelli, Federico": ("Venice", "威尼斯画家 (Milanese origin)"),
    "Cesi, Bishop Angelo": ("Rome", "罗马主教/赞助人"),

    # --- Seventh Pass Variations (Single Instance Targets) ---
    "Bussi, Francesca": ("Rome", "罗马女画家"),
    "Cadani, Stefano": ("Rome", "罗马艺术家"),
    "Cadogan, Lord": ("London", "英国贵族/收藏家"),
    "Caime": ("Venice", "威尼斯画家 (Caime)"),
    "Camerino, Giovanni Angelo da": ("Rome", "罗马建筑师"),
    "Campione, Giovanni da": ("Milan", "米兰雕塑家"),
    "Canal, Fabio": ("Venice", "威尼斯画家"),
    "Canal, Gerolamo": ("Venice", "威尼斯贵族"),
    "Canale, Procuratore": ("Venice", "威尼斯检察官"),
    "Cappello, Antonio": ("Venice", "威尼斯贵族"),
    "Caprara, Marshal": ("Vienna", "奥地利元帅"),
    "Caraboli, Giacomo": ("Bologna", "博洛尼亚画家"),
    "Carandini, Count Camillo": ("Modena", "摩德纳贵族"),
    "Carandini, Marchesa Elisa": ("Modena", "摩德纳贵族"),
    "Carlo, Ferrante": ("Bologna", "博洛尼亚画家"),
    "Carpegna, Count": ("Rome", "罗马贵族"),
    "Cars, Laurence": ("Paris", "法国版画家"),
    "Castelli, Matteo": ("Rome", "罗马建筑师"),
    "Castro, Jacomo di": ("Naples", "那不勒斯画家"),
    "Catalano, Francesco": ("Naples", "那不勒斯画家"),
    "Cattaneo, Giovanni de": ("Milan", "米兰雕塑家"),
    "Cavazza, Conte": ("Bologna", "博洛尼亚贵族"),
    "Celle, Georg Wilhelm Duke of": ("Celle", "不伦瑞克-吕讷堡公爵"),
    "Celotti, Abate Luigi": ("Venice", "威尼斯修道院院长/收藏家"),
    "Cerato, Abate": ("Padua", "帕多瓦建筑师"),
    "Cesi, Cardinal Pier Donato": ("Rome", "罗马红衣主教"),
    "Cesi, Prince Federico": ("Rome", "林琴学院创始人"),
    "Ceva, Cardinal": ("Rome", "罗马红衣主教"),
    "Chandos, James Brydges, 1st Duke of": ("London", "英国贵族，Canons庄园主"),
    "Chantelou, Paul-Fréart de": ("Paris", "法国收藏家 (Bernini日记作者)"),
    "Chardin, Jean Baptiste Siméon": ("Paris", "法国静物/风俗画家"),
    "Charles II of Spain": ("Madrid", "西班牙国王"),
    "Charles V, Holy Roman Emperor": ("Madrid/Vienna", "神圣罗马帝国皇帝"),
    "Chi soffre, speri": ("Rome", "罗马歌剧 (Mazzocchi/Marazzoli)"),
    "Chiari, Giuseppe and Tommaso": ("Rome", "罗马画家兄弟"),
    "Chiarini, Marcantonio": ("Bologna", "博洛尼亚透视画家"),
    "Chigi, Agostino 'il Magnifico'": ("Rome", "文艺复兴银行家"),
    "Chigi, Agostino (nephew to Alexander VII)": ("Rome", "罗马贵族"),
    "Chigi, Don Mario (brother to Pope Alexander VII)": ("Rome", "罗马贵族"),
    "Churches of religious orders": ("Europe", "修会教堂"),
    "Ciarpi, Baccio": ("Florence/Rome", "画家 (Pietro da Cortona老师)"),
    "Cibo palace": ("Rome", "罗马奇博宫"),
    "Città di Castello, Matteo da": ("Rome", "文艺复兴建筑师"),
    "Clemens August, Archbishop-Elector of Cologne": ("Cologne", "科隆选帝侯"),
    "Clement, Abbé": ("Paris", "法国评论家"),
    "Clement VIII, Pope": ("Rome", "教皇克莱门特八世"),
    "Clement IX, Pope": ("Rome", "教皇克莱门特九世"),
    "Clement X, Pope": ("Rome", "教皇克莱门特十世"),
    "Clement XI, Pope": ("Rome", "教皇克莱门特十一世"),
    "Clement XII, Pope": ("Rome", "教皇克莱门特十二世"),
}

def enrich_all_files():
    print("--- Applying Massive Knowledge Base Enrichment ---")
    files = [f for f in os.listdir(enrich_dir) if f.endswith("_refined.csv")]
    
    total_updated_entries = 0
    
    for filename in files:
        path = os.path.join(enrich_dir, filename)
        try:
            df = pd.read_csv(path)
            
            # Ensure columns exist
            if 'Proposed Location' not in df.columns:
                df['Proposed Location'] = ""
            if '备注/来源' not in df.columns:
                df['备注/来源'] = ""
            
            updated_in_file = 0
            
            for index, row in df.iterrows():
                term = str(row['Index_Main Entry']).strip()
                clean_term = term.strip("'")
                
                # Only update if currently empty
                current_loc = str(row['Proposed Location'])
                if current_loc and current_loc != "nan" and current_loc.strip() != "":
                    continue

                loc = ""
                reason_cn = ""
                
                # Try exact match
                if term in kb_full:
                    loc, reason_cn = kb_full[term]
                # Try clean match
                elif clean_term in kb_full:
                    loc, reason_cn = kb_full[clean_term]
                # Try fuzzy/partial match for common patterns
                else:
                    # Handle "Family"
                    if "family" in term.lower():
                        base_name = term.split()[0] + " family"
                        if base_name in kb_full:
                            loc, reason_cn = kb_full[base_name]
                    
                    # Handle "Cardinal"
                    if not loc and "Cardinal" in term:
                        # Try to find just the surname in KB
                        parts = term.replace(",", "").split()
                        for p in parts:
                            if p in kb_full: # Unlikely but possible
                                pass
                
                # Update if found
                if loc:
                    df.at[index, 'Proposed Location'] = loc
                    df.at[index, '备注/来源'] = reason_cn
                    updated_in_file += 1
            
            if updated_in_file > 0:
                df.to_csv(path, index=False, encoding='utf-8-sig')
                print(f"Updated {filename}: {updated_in_file} entries enriched.")
                total_updated_entries += updated_in_file
            else:
                print(f"No new matches in {filename}")
                
        except Exception as e:
            print(f"Error processing {filename}: {e}")
            
    print(f"Total entries enriched across all files: {total_updated_entries}")

if __name__ == "__main__":
    enrich_all_files()
